export const Province = [
  { id: 1, fa: "آذربایجان شرقی", en: "East Azerbaijan" },
  { id: 2, fa: "آذربایجان غربی", en: "West Azerbaijan" },
  { id: 3, fa: "اردبیل", en: "Ardabil" },
  { id: 4, fa: "اصفهان", en: "Isfahan" },
  { id: 5, fa: "البرز", en: "Alborz" },
  { id: 6, fa: "ایلام", en: "Ilam" },
  { id: 7, fa: "بوشهر", en: "Bushehr" },
  { id: 8, fa: "تهران", en: "Tehran" },
  { id: 9, fa: "چهارمحال و بختیاری", en: "Chahar Bakhtiari" },
  { id: 10, fa: "خراسان جنوبی", en: "South Khorasan" },
  { id: 11, fa: "خراسان رضوی", en: "Razavi Khorasan" },
  { id: 12, fa: "خراسان شمالی", en: "North Khorasan" },
  { id: 13, fa: "خوزستان", en: "Khuzestan" },
  { id: 14, fa: "زنجان", en: "Zanjan" },
  { id: 15, fa: "سمنان", en: "Semnan" },
  { id: 16, fa: "سیستان و بلوچستان", en: "Sistan Baluchistan" },
  { id: 17, fa: "فارس", en: "Fars" },
  { id: 18, fa: "قزوین", en: "Qazvin" },
  { id: 19, fa: "قم", en: "Qom" },
  { id: 20, fa: "کردستان", en: "Kurdistan" },
  { id: 21, fa: "کرمان", en: "Kerman" },
  { id: 22, fa: "کرمانشاه", en: "Kermanshah" },
  { id: 23, fa: "کهگیلویه و بویراحمد", en: "Kohgiluyeh Boyer-Ahmad" },
  { id: 24, fa: "گلستان", en: "Golestan" },
  { id: 25, fa: "گیلان", en: "Gilan" },
  { id: 26, fa: "مازندران", en: "Mazandaran" },
  { id: 27, fa: "هرمزگان", en: "Hormozgan" },
  { id: 28, fa: "همدان", en: "Hamadan" },
  { id: 29, fa: "یزد", en: "Yazd" },
];

export const Cities = [
  { id: 1, fa: "تبريز", en: "Tabriz", provinceId: 1 },
  { id: 2, fa: "كندوان", en: "kandovan", provinceId: 1 },
  { id: 3, fa: "بندر شرفخانه", en: "Sharafkhaneh", provinceId: 1 },
  { id: 4, fa: "مراغه", en: "Maragheh", provinceId: 1 },
  { id: 5, fa: "ميانه", en: "Mianeh", provinceId: 1 },
  { id: 6, fa: "شبستر", en: "Shabestar", provinceId: 1 },
  { id: 7, fa: "مرند", en: "Marand", provinceId: 1 },
  { id: 8, fa: "جلفا", en: "Jolfa", provinceId: 1 },
  { id: 9, fa: "سراب", en: "Sarab", provinceId: 1 },
  { id: 10, fa: "هاديشهر", en: "Hadishahr", provinceId: 1 },
  { id: 11, fa: "بناب", en: "Bonab", provinceId: 1 },
  { id: 12, fa: "كليبر", en: "Kaleybar", provinceId: 1 },
  { id: 13, fa: "تسوج", en: "Tasuj", provinceId: 1 },
  { id: 14, fa: "اهر", en: "Ahar", provinceId: 1 },
  { id: 15, fa: "هريس", en: "Heris", provinceId: 1 },
  { id: 16, fa: "عجبشير", en: "Ajab Shir", provinceId: 1 },
  { id: 17, fa: "هشترود", en: "Hashtrud", provinceId: 1 },
  { id: 18, fa: "ملكان", en: "Malekan", provinceId: 1 },
  { id: 19, fa: "بستان آباد", en: "Bastan", provinceId: 1 },
  { id: 20, fa: "ورزقان", en: "Varzaqan", provinceId: 1 },
  { id: 21, fa: "اسكو", en: "Osku", provinceId: 1 },
  { id: 22, fa: "آذر شهر", en: "Azarshahr", provinceId: 1 },
  { id: 23, fa: "قره آغاج", en: "Qarah Aghaj", provinceId: 1 },
  { id: 24, fa: "ممقان", en: "Mamqan", provinceId: 1 },
  { id: 25, fa: "صوفیان", en: "Sufian", provinceId: 1 },
  { id: 26, fa: "ایلخچی", en: "Ilkhchi", provinceId: 1 },
  { id: 27, fa: "خسروشهر", en: "Khosrowshahr", provinceId: 1 },
  { id: 28, fa: "باسمنج", en: "Basmenj", provinceId: 1 },
  { id: 29, fa: "سهند", en: "Sahand", provinceId: 1 },
  { id: 30, fa: "اروميه", en: "Urmia", provinceId: 2 },
  { id: 31, fa: "نقده", en: "Naqadeh", provinceId: 2 },
  { id: 32, fa: "ماكو", en: "Maku", provinceId: 2 },
  { id: 33, fa: "تكاب", en: "Takab", provinceId: 2 },
  { id: 34, fa: "خوي", en: "Khoy", provinceId: 2 },
  { id: 35, fa: "مهاباد", en: "Mahabad", provinceId: 2 },
  { id: 36, fa: "سر دشت", en: "Sardasht", provinceId: 2 },
  { id: 37, fa: "چالدران", en: "Chaldaran", provinceId: 2 },
  { id: 38, fa: "بوكان", en: "Bukan", provinceId: 2 },
  { id: 39, fa: "مياندوآب", en: "Miandoab", provinceId: 2 },
  { id: 40, fa: "سلماس", en: "Salmas", provinceId: 2 },
  { id: 41, fa: "شاهين دژ", en: "Shahin Dezh", provinceId: 2 },
  { id: 42, fa: "پيرانشهر", en: "Piranshahr", provinceId: 2 },
  { id: 43, fa: "سيه چشمه", en: "Siah Cheshmeh", provinceId: 2 },
  { id: 44, fa: "اشنويه", en: "Oshnavieh", provinceId: 2 },
  { id: 45, fa: "چایپاره", en: "Chaipare", provinceId: 2 },
  { id: 46, fa: "پلدشت", en: "Poldasht", provinceId: 2 },
  { id: 47, fa: "شوط", en: "Showt", provinceId: 2 },
  { id: 48, fa: "اردبيل", en: "Ardabil", provinceId: 3 },
  { id: 49, fa: "سرعين", en: "Sareyn", provinceId: 3 },
  { id: 50, fa: "بيله سوار", en: "Bileh Savar", provinceId: 3 },
  { id: 51, fa: "پارس آباد", en: "Parsabad", provinceId: 3 },
  { id: 52, fa: "خلخال", en: "Khalkhal", provinceId: 3 },
  { id: 53, fa: "مشگين شهر", en: "Meshginshahr", provinceId: 3 },
  { id: 54, fa: "مغان", en: "Moghan", provinceId: 3 },
  { id: 55, fa: "نمين", en: "Namin", provinceId: 3 },
  { id: 56, fa: "نير", en: "Nir", provinceId: 3 },
  { id: 57, fa: "كوثر", en: "Kosar", provinceId: 3 },
  { id: 58, fa: "كيوي", en: "Kivi", provinceId: 3 },
  { id: 59, fa: "گرمي", en: "Germi", provinceId: 3 },
  { id: 60, fa: "اصفهان", en: "Isfahan", provinceId: 4 },
  { id: 61, fa: "فريدون شهر", en: "Fereydunshahr", provinceId: 4 },
  { id: 62, fa: "فلاورجان", en: "Falavarjan", provinceId: 4 },
  { id: 63, fa: "گلپايگان", en: "Golpayegan", provinceId: 4 },
  { id: 64, fa: "دهاقان", en: "Dehaqan", provinceId: 4 },
  { id: 65, fa: "نطنز", en: "Natanz", provinceId: 4 },
  { id: 66, fa: "نايين", en: "Nain", provinceId: 4 },
  { id: 67, fa: "تيران", en: "Tiran", provinceId: 4 },
  { id: 68, fa: "كاشان", en: "Kashan", provinceId: 4 },
  { id: 69, fa: "فولاد شهر", en: "Fuladshahr", provinceId: 4 },
  { id: 70, fa: "فريدن", en: "Fereydan", provinceId: 4 },
  { id: 71, fa: "سميرم", en: "Semirom", provinceId: 4 },
  { id: 72, fa: "درچه", en: "Dorcheh", provinceId: 4 },
  { id: 73, fa: "کوهپایه", en: "Kuhpayeh", provinceId: 4 },
  { id: 74, fa: "مباركه", en: "Mobarakeh", provinceId: 4 },
  { id: 75, fa: "شهرضا", en: "Shahreza", provinceId: 4 },
  { id: 76, fa: "خميني شهر", en: "Khomeyni Shahr", provinceId: 4 },
  { id: 77, fa: "شاهين شهر", en: "Shahin Shahr", provinceId: 4 },
  { id: 78, fa: "نجف آباد", en: "Najafabad", provinceId: 4 },
  { id: 79, fa: "دولت آباد", en: "Dolatabad", provinceId: 4 },
  { id: 80, fa: "زرين شهر", en: "Zarrin Shahr", provinceId: 4 },
  { id: 81, fa: "آران و بيدگل", en: "Aran Bidgol", provinceId: 4 },
  { id: 82, fa: "باغ بهادران", en: "Bagh-e Bahadoran", provinceId: 4 },
  { id: 83, fa: "خوانسار", en: "Khansar", provinceId: 4 },
  { id: 84, fa: "مهردشت", en: "Mehrdasht", provinceId: 4 },
  { id: 85, fa: "علويجه", en: "Alavicheh", provinceId: 4 },
  { id: 86, fa: "عسگران", en: "Asgaran", provinceId: 4 },
  { id: 87, fa: "نهضت آباد", en: "Nehzat Abad", provinceId: 4 },
  { id: 88, fa: "حاجي آباد", en: "Haji Abad", provinceId: 4 },
  { id: 89, fa: "تودشک", en: "Tudeshk", provinceId: 4 },
  { id: 90, fa: "ورزنه", en: "Varzaneh", provinceId: 4 },
  { id: 91, fa: "اردستان", en: "Ardestan", provinceId: 4 },
  { id: 92, fa: "کرج", en: "Karaj", provinceId: 5 },
  { id: 93, fa: "فردیس", en: "Fardis", provinceId: 5 },
  { id: 94, fa: "کمال‌شهر", en: "Kamal shahr", provinceId: 5 },
  { id: 95, fa: "نظرآباد", en: "Nazarabad", provinceId: 5 },
  { id: 96, fa: "محمدشهر", en: "Mohammad shahr", provinceId: 5 },
  { id: 97, fa: "ماهدشت", en: "Mahdasht", provinceId: 5 },
  { id: 98, fa: "مشکین‌دشت", en: "Meshginshahr", provinceId: 5 },
  { id: 99, fa: "هشتگرد", en: "Hashtgerd", provinceId: 5 },
  { id: 100, fa: "چهارباغ", en: "Chaharbagh", provinceId: 5 },
  { id: 101, fa: "اشتهارد", en: "Eshtehard", provinceId: 5 },
  { id: 102, fa: "گرمدره", en: "Garmdarreh", provinceId: 5 },
  { id: 103, fa: "گلسار", en: "Golsar", provinceId: 5 },
  { id: 104, fa: "کوهسار", en: "Kosar", provinceId: 5 },
  { id: 105, fa: "تنکمان", en: "Tankaman", provinceId: 5 },
  { id: 106, fa: "طالقان", en: "Taleghan", provinceId: 5 },
  { id: 107, fa: "آسارا", en: "Asara", provinceId: 5 },
  { id: 108, fa: "پلنگ‌آباد", en: "palangabad", provinceId: 5 },
  { id: 109, fa: "ايلام", en: "Ilam", provinceId: 6 },
  { id: 110, fa: "مهران", en: "Mehran", provinceId: 6 },
  { id: 111, fa: "دهلران", en: "Dehloran", provinceId: 6 },
  { id: 112, fa: "آبدانان", en: "Abdanan", provinceId: 6 },
  { id: 113, fa: "دره شهر", en: "Darreh shahr", provinceId: 6 },
  { id: 114, fa: "ايوان", en: "Eyvan", provinceId: 6 },
  { id: 115, fa: "سرابله", en: "Sarableh", provinceId: 6 },
  { id: 116, fa: "بوشهر", en: "Bushehr", provinceId: 7 },
  { id: 117, fa: "تنگستان", en: "Tang-e", provinceId: 7 },
  { id: 118, fa: "دشتستان", en: "dashtestan", provinceId: 7 },
  { id: 119, fa: "دير", en: "Deyr", provinceId: 7 },
  { id: 120, fa: "ديلم", en: "Deylam", provinceId: 7 },
  { id: 121, fa: "كنگان", en: "Kangan", provinceId: 7 },
  { id: 122, fa: "گناوه", en: "Ganaveh", provinceId: 7 },
  { id: 123, fa: "ريشهر", en: "Rig shahr", provinceId: 7 },
  { id: 124, fa: "دشتي", en: "Dashti", provinceId: 7 },
  { id: 125, fa: "خورموج", en: "Khormoj", provinceId: 7 },
  { id: 126, fa: "اهرم", en: "Ahram", provinceId: 7 },
  { id: 127, fa: "برازجان", en: "Borazjan", provinceId: 7 },
  { id: 128, fa: "خارك", en: "Kharg", provinceId: 7 },
  { id: 129, fa: "جم", en: "Germi", provinceId: 7 },
  { id: 130, fa: "کاکی", en: "Kaki", provinceId: 7 },
  { id: 131, fa: "عسلویه", en: "Asaluyeh", provinceId: 7 },
  { id: 132, fa: "بردخون", en: "Bordkhon", provinceId: 7 },
  { id: 133, fa: "تهران", en: "Tehran", provinceId: 8 },
  { id: 134, fa: "ورامين", en: "Varamin", provinceId: 8 },
  { id: 135, fa: "فيروزكوه", en: "Firuzkuh", provinceId: 8 },
  { id: 136, fa: "ري", en: "rey", provinceId: 8 },
  { id: 137, fa: "دماوند", en: "Damavand", provinceId: 8 },
  { id: 138, fa: "اسلامشهر", en: "Eslamshahr", provinceId: 8 },
  { id: 139, fa: "رودهن", en: "Rudehen", provinceId: 8 },
  { id: 140, fa: "لواسان", en: "Lavasan", provinceId: 8 },
  { id: 141, fa: "بومهن", en: "Bumahen", provinceId: 8 },
  { id: 142, fa: "تجريش", en: "tajrish", provinceId: 8 },
  { id: 143, fa: "فشم", en: "fasham", provinceId: 8 },
  { id: 144, fa: "كهريزك", en: "Kahrizak", provinceId: 8 },
  { id: 145, fa: "پاكدشت", en: "Pakdasht", provinceId: 8 },
  { id: 146, fa: "چهاردانگه", en: "Chahardangeh", provinceId: 8 },
  { id: 147, fa: "شريف آباد", en: "Sharifabad", provinceId: 8 },
  { id: 148, fa: "قرچك", en: "Qarchek", provinceId: 8 },
  { id: 149, fa: "باقرشهر", en: "bagher shahr", provinceId: 8 },
  { id: 150, fa: "شهريار", en: "Shahriar", provinceId: 8 },
  { id: 151, fa: "رباط كريم", en: "Robat Karim", provinceId: 8 },
  { id: 152, fa: "قدس", en: "Qods", provinceId: 8 },
  { id: 153, fa: "ملارد", en: "Malard", provinceId: 8 },
  { id: 154, fa: "شهركرد", en: "shahrekord", provinceId: 9 },
  { id: 155, fa: "فارسان", en: "Farsan", provinceId: 9 },
  { id: 156, fa: "بروجن", en: "Borazjan", provinceId: 9 },
  { id: 157, fa: "چلگرد", en: "Chelgard", provinceId: 9 },
  { id: 158, fa: "اردل", en: "Ardal", provinceId: 9 },
  { id: 159, fa: "لردگان", en: "Lordegan", provinceId: 9 },
  { id: 160, fa: "سامان", en: "Saman", provinceId: 9 },
  { id: 161, fa: "قائن", en: "Qaen", provinceId: 10 },
  { id: 162, fa: "فردوس", en: "Ferdows", provinceId: 10 },
  { id: 163, fa: "بيرجند", en: "Birjand", provinceId: 10 },
  { id: 164, fa: "نهبندان", en: "Nahbandan", provinceId: 10 },
  { id: 165, fa: "سربيشه", en: "Sarbisheh", provinceId: 10 },
  { id: 166, fa: "طبس مسینا", en: "Tabas Masina", provinceId: 10 },
  { id: 167, fa: "قهستان", en: "Qahestan", provinceId: 10 },
  { id: 168, fa: "درمیان", en: "Darmian", provinceId: 10 },
  { id: 169, fa: "مشهد", en: "Mashhad", provinceId: 11 },
  { id: 170, fa: "نيشابور", en: "Neyshabour", provinceId: 11 },
  { id: 171, fa: "سبزوار", en: "Sabzevar", provinceId: 11 },
  { id: 172, fa: "كاشمر", en: "Kashan", provinceId: 11 },
  { id: 173, fa: "گناباد", en: "Gonabad", provinceId: 11 },
  { id: 174, fa: "طبس", en: "Tabas", provinceId: 11 },
  { id: 175, fa: "تربت حيدريه", en: "Torbat heydarie", provinceId: 11 },
  { id: 176, fa: "خواف", en: "khoaf", provinceId: 11 },
  { id: 177, fa: "تربت جام", en: "torbat jam", provinceId: 11 },
  { id: 178, fa: "تايباد", en: "Taybad", provinceId: 11 },
  { id: 179, fa: "قوچان", en: "Quchan", provinceId: 11 },
  { id: 180, fa: "بردسكن", en: "bberdeskan", provinceId: 11 },
  { id: 181, fa: "فريمان", en: "Fariman", provinceId: 11 },
  { id: 182, fa: "چناران", en: "Chenaran", provinceId: 11 },
  { id: 183, fa: "درگز", en: "Dargaz", provinceId: 11 },
  { id: 184, fa: "كلات", en: "Kalat", provinceId: 11 },
  { id: 185, fa: "طرقبه", en: "Torqabeh", provinceId: 11 },
  { id: 186, fa: "سر ولایت", en: "Velayat", provinceId: 11 },
  { id: 187, fa: "بجنورد", en: "Bojnord", provinceId: 12 },
  { id: 188, fa: "اسفراين", en: "Esfarayen", provinceId: 12 },
  { id: 189, fa: "جاجرم", en: "Jajarm", provinceId: 12 },
  { id: 190, fa: "شيروان", en: "Shirvan", provinceId: 12 },
  { id: 191, fa: "آشخانه", en: "Ashkhaneh", provinceId: 12 },
  { id: 193, fa: "گرمه", en: "Garmeh", provinceId: 12 },
  { id: 194, fa: "ساروج", en: "Sarouj", provinceId: 12 },
  { id: 195, fa: "اهواز", en: "Ahvaz", provinceId: 13 },
  { id: 196, fa: "ايرانشهر", en: "Iranshahr", provinceId: 13 },
  { id: 197, fa: "شوش", en: "Shush", provinceId: 13 },
  { id: 198, fa: "آبادان", en: "Abadan", provinceId: 13 },
  { id: 199, fa: "خرمشهر", en: "khoramshahr", provinceId: 13 },
  { id: 200, fa: "مسجد سليمان", en: "Masjed Soleyman", provinceId: 13 },
  { id: 201, fa: "ايذه", en: "Ize", provinceId: 13 },
  { id: 202, fa: "شوشتر", en: "Shushtar", provinceId: 13 },
  { id: 203, fa: "انديمشك", en: "Andimeshk", provinceId: 13 },
  { id: 204, fa: "سوسنگرد", en: "sousangard", provinceId: 13 },
  { id: 205, fa: "هويزه", en: "hoveyze", provinceId: 13 },
  { id: 206, fa: "دزفول", en: "Dezful", provinceId: 13 },
  { id: 207, fa: "شادگان", en: "Shadegan", provinceId: 13 },
  { id: 208, fa: "بندر ماهشهر", en: "Bandar Mahshahr", provinceId: 13 },
  {
    id: 209,
    fa: "بندر امام خميني",
    en: "Bandar Emam khomeyni",
    provinceId: 13,
  },
  { id: 210, fa: "اميديه", en: "Omidiyeh", provinceId: 13 },
  { id: 211, fa: "بهبهان", en: "Behbahan", provinceId: 13 },
  { id: 212, fa: "رامهرمز", en: "Ramhormoz", provinceId: 13 },
  { id: 213, fa: "باغ ملك", en: "Bagh Malek", provinceId: 13 },
  { id: 214, fa: "هنديجان", en: "Hendijan", provinceId: 13 },
  { id: 215, fa: "لالي", en: "Lali", provinceId: 13 },
  { id: 216, fa: "رامشیر", en: "Ramshir", provinceId: 13 },
  { id: 217, fa: "حمیدیه", en: "Hamidiyeh", provinceId: 13 },
  { id: 218, fa: "دغاغله", en: "daghaghele", provinceId: 13 },
  { id: 219, fa: "ملاثانی", en: "molasani", provinceId: 13 },
  { id: 220, fa: "شادگان", en: "Shadegan", provinceId: 13 },
  { id: 221, fa: "ویسی", en: "veysi", provinceId: 13 },
  { id: 222, fa: "زنجان", en: "Zanjan", provinceId: 14 },
  { id: 223, fa: "ابهر", en: "Abhar", provinceId: 14 },
  { id: 224, fa: "خدابنده", en: "khodabande", provinceId: 14 },
  { id: 225, fa: "طارم", en: "tarom", provinceId: 14 },
  { id: 226, fa: "ماهنشان", en: "Mahneshan", provinceId: 14 },
  { id: 227, fa: "خرمدره", en: "Khorramdarreh", provinceId: 14 },
  { id: 228, fa: "ايجرود", en: "Ijrud", provinceId: 14 },
  { id: 229, fa: "زرين آباد", en: "Zarrin Abad", provinceId: 14 },
  { id: 230, fa: "آب بر", en: "Ab Bar", provinceId: 14 },
  { id: 231, fa: "قيدار", en: "Qedarites", provinceId: 14 },
  { id: 232, fa: "سمنان", en: "Semnan", provinceId: 15 },
  { id: 233, fa: "شاهرود", en: "Shahrud", provinceId: 15 },
  { id: 234, fa: "گرمسار", en: "Garmsar", provinceId: 15 },
  { id: 235, fa: "ايوانكي", en: "Eyvanki", provinceId: 15 },
  { id: 236, fa: "دامغان", en: "Damghan", provinceId: 15 },
  { id: 237, fa: "بسطام", en: "Bastam", provinceId: 15 },
  { id: 238, fa: "زاهدان", en: "Zahedan", provinceId: 16 },
  { id: 239, fa: "چابهار", en: "Chabahar", provinceId: 16 },
  { id: 240, fa: "خاش", en: "Khash", provinceId: 16 },
  { id: 241, fa: "سراوان", en: "Saravan", provinceId: 16 },
  { id: 242, fa: "زابل", en: "Zabol", provinceId: 16 },
  { id: 243, fa: "سرباز", en: "Sarbaz", provinceId: 16 },
  { id: 244, fa: "نيكشهر", en: "Nik Shahr", provinceId: 16 },
  { id: 245, fa: "ايرانشهر", en: "Iranshahr", provinceId: 16 },
  { id: 246, fa: "راسك", en: "Rasak", provinceId: 16 },
  { id: 247, fa: "ميرجاوه", en: "Mirjaveh", provinceId: 16 },
  { id: 248, fa: "شيراز", en: "Shiraz", provinceId: 17 },
  { id: 249, fa: "اقليد", en: "Eqlid", provinceId: 17 },
  { id: 250, fa: "داراب", en: "Darab", provinceId: 17 },
  { id: 251, fa: "فسا", en: "Fasa", provinceId: 17 },
  { id: 252, fa: "مرودشت", en: "Marvdasht", provinceId: 17 },
  { id: 253, fa: "خرم بيد", en: "Khorrambid", provinceId: 17 },
  { id: 254, fa: "آباده", en: "Abadeh", provinceId: 17 },
  { id: 255, fa: "كازرون", en: "Kazerun", provinceId: 17 },
  { id: 256, fa: "ممسني", en: "Mamasani", provinceId: 17 },
  { id: 257, fa: "سپيدان", en: "Sepidan", provinceId: 17 },
  { id: 258, fa: "لار", en: "Lar", provinceId: 17 },
  { id: 259, fa: "فيروز آباد", en: "Firuzabad", provinceId: 17 },
  { id: 260, fa: "جهرم", en: "Mirjaveh", provinceId: 17 },
  { id: 261, fa: "ني ريز", en: "Mirjaveh", provinceId: 17 },
  { id: 262, fa: "استهبان", en: "Mirjaveh", provinceId: 17 },
  { id: 263, fa: "لامرد", en: "Mirjaveh", provinceId: 17 },
  { id: 264, fa: "مهر", en: "Mirjaveh", provinceId: 17 },
  { id: 265, fa: "حاجي آباد", en: "Mirjaveh", provinceId: 17 },
  { id: 266, fa: "نورآباد", en: "Mirjaveh", provinceId: 17 },
  { id: 267, fa: "اردكان", en: "Mirjaveh", provinceId: 17 },
  { id: 268, fa: "صفاشهر", en: "Mirjaveh", provinceId: 17 },
  { id: 269, fa: "ارسنجان", en: "Mirjaveh", provinceId: 17 },
  { id: 290, fa: "قيروكارزين", en: "Mirjaveh", provinceId: 17 },
  { id: 291, fa: "سوريان", en: "Mirjaveh", provinceId: 17 },
  { id: 292, fa: "فراشبند", en: "Mirjaveh", provinceId: 17 },
  { id: 293, fa: "سروستان", en: "Mirjaveh", provinceId: 17 },
  { id: 294, fa: "ارژن", en: "Mirjaveh", provinceId: 17 },
  { id: 295, fa: "گويم", en: "Mirjaveh", provinceId: 17 },
  { id: 296, fa: "داريون", en: "Mirjaveh", provinceId: 17 },
  { id: 297, fa: "زرقان", en: "Mirjaveh", provinceId: 17 },
  { id: 298, fa: "خان زنیان", en: "Mirjaveh", provinceId: 17 },
  { id: 299, fa: "کوار", en: "Mirjaveh", provinceId: 17 },
  { id: 300, fa: "ده بید", en: "Mirjaveh", provinceId: 17 },
  { id: 301, fa: "باب انار/خفر", en: "Mirjaveh", provinceId: 17 },
  { id: 302, fa: "بوانات", en: "Mirjaveh", provinceId: 17 },
  { id: 303, fa: "خرامه", en: "Mirjaveh", provinceId: 17 },
  { id: 304, fa: "خنج", en: "Mirjaveh", provinceId: 17 },
  { id: 305, fa: "سیاخ دارنگون", en: "Mirjaveh", provinceId: 17 },
  { id: 306, fa: "قزوين", en: "Qazvin", provinceId: 18 },
  { id: 307, fa: "تاكستان", en: "Takestan", provinceId: 18 },
  { id: 308, fa: "آبيك", en: "Abyek", provinceId: 18 },
  { id: 309, fa: "بوئين زهرا", en: "Buin Zahra", provinceId: 18 },
  { id: 310, fa: "قم", en: "Qom", provinceId: 19 },
  { id: 311, fa: "سنندج", en: "Sanandaj", provinceId: 20 },
  { id: 312, fa: "ديواندره", en: "Divandarreh", provinceId: 20 },
  { id: 313, fa: "بانه", en: "Baneh", provinceId: 20 },
  { id: 314, fa: "بيجار", en: "Bijar", provinceId: 20 },
  { id: 315, fa: "سقز", en: "Saqqez", provinceId: 20 },
  { id: 316, fa: "كامياران", en: "Kamyaran", provinceId: 20 },
  { id: 317, fa: "قروه", en: "Qorveh", provinceId: 20 },
  { id: 318, fa: "مريوان", en: "Marivan", provinceId: 20 },
  { id: 319, fa: "صلوات آباد", en: "Salavat Abad", provinceId: 20 },
  { id: 320, fa: "حسن آباد", en: "Hasan Abad", provinceId: 20 },
  { id: 321, fa: "كرمان", en: "Kerman", provinceId: 21 },
  { id: 322, fa: "راور", en: "Ravar", provinceId: 21 },
  { id: 323, fa: "بابك", en: "Babak", provinceId: 21 },
  { id: 324, fa: "انار", en: "Anar", provinceId: 21 },
  { id: 325, fa: "کوهبنان", en: "Kuhbanan", provinceId: 21 },
  { id: 326, fa: "رفسنجان", en: "Rafsanjan", provinceId: 21 },
  { id: 327, fa: "بافت", en: "Baft", provinceId: 21 },
  { id: 328, fa: "سيرجان", en: "Sirjan", provinceId: 21 },
  { id: 329, fa: "كهنوج", en: "Kahnuj", provinceId: 21 },
  { id: 330, fa: "زرند", en: "Zarand", provinceId: 21 },
  { id: 331, fa: "بم", en: "Bam", provinceId: 21 },
  { id: 332, fa: "جيرفت", en: "Jiroft", provinceId: 21 },
  { id: 333, fa: "كرمانشاه", en: "Kermanshah", provinceId: 22 },
  { id: 334, fa: "اسلام آباد غرب", en: "Eslamabad-e West", provinceId: 22 },
  { id: 335, fa: "سر پل ذهاب", en: "Sarpol-e Zahab", provinceId: 22 },
  { id: 336, fa: "كنگاور", en: "Kangavar", provinceId: 22 },
  { id: 337, fa: "سنقر", en: "Sanqer", provinceId: 22 },
  { id: 338, fa: "قصر شيرين", en: "Qasr-e Shirin", provinceId: 22 },
  { id: 339, fa: "گيلان غرب", en: "Gilan", provinceId: 22 },
  { id: 340, fa: "هرسين", en: "Harsin", provinceId: 22 },
  { id: 341, fa: "صحنه", en: "Sahneh", provinceId: 22 },
  { id: 342, fa: "پاوه", en: "Paveh", provinceId: 22 },
  { id: 343, fa: "جوانرود", en: "Javanrud", provinceId: 22 },
  { id: 344, fa: "شاهو", en: "Shahu", provinceId: 22 },
  { id: 345, fa: "یاسوج", en: "Yasuj", provinceId: 23 },
  { id: 346, fa: "گچساران", en: "Gachsaran", provinceId: 23 },
  { id: 347, fa: "دنا", en: "Dena", provinceId: 23 },
  { id: 348, fa: "دوگنبدان", en: "?Dogonbadan", provinceId: 23 },
  { id: 349, fa: "سي سخت", en: "Sisakht", provinceId: 23 },
  { id: 350, fa: "دهدشت", en: "Dehdasht", provinceId: 23 },
  { id: 351, fa: "ليكك", en: "Likak", provinceId: 23 },
  { id: 352, fa: "گرگان", en: "Gorgan", provinceId: 24 },
  { id: 353, fa: "آق قلا", en: "Aqqala", provinceId: 24 },
  { id: 354, fa: "گنبد كاووس", en: "Gonabad Kavus", provinceId: 24 },
  { id: 355, fa: "علي آباد كتول", en: "Aliabad-e Katul", provinceId: 24 },
  { id: 356, fa: "مينو دشت", en: "Minudasht", provinceId: 24 },
  { id: 357, fa: "تركمن", en: "Torkaman", provinceId: 24 },
  { id: 358, fa: "كردكوي", en: "Kordkuy", provinceId: 24 },
  { id: 359, fa: "بندر گز", en: "Bandar-e Gaz", provinceId: 24 },
  { id: 360, fa: "كلاله", en: "Kalaleh", provinceId: 24 },
  { id: 361, fa: "آزاد شهر", en: "Azadshahr", provinceId: 24 },
  { id: 362, fa: "راميان", en: "Ramian", provinceId: 24 },
  { id: 363, fa: "رشت", en: "Rasht", provinceId: 25 },
  { id: 367, fa: "منجیل", en: "Manjil", provinceId: 25 },
  { id: 368, fa: "لنگرود", en: "Langarud", provinceId: 25 },
  { id: 369, fa: "رود سر", en: "Rudsar", provinceId: 25 },
  { id: 370, fa: "تالش", en: "Talesh", provinceId: 25 },
  { id: 371, fa: "آستارا", en: "Astara", provinceId: 25 },
  { id: 372, fa: "ماسوله", en: "Masuleh", provinceId: 25 },
  { id: 373, fa: "آستانه اشرفيه", en: "Astaneh-ye Ashrafiyeh", provinceId: 25 },
  { id: 374, fa: "رودبار", en: "Rudbar", provinceId: 25 },
  { id: 375, fa: "فومن", en: "Fuman", provinceId: 25 },
  { id: 376, fa: "صومعه سرا", en: "Sowme Sara", provinceId: 25 },
  { id: 377, fa: "بندرانزلي", en: "Bandar-e Anzali", provinceId: 25 },
  { id: 378, fa: "كلاچاي", en: "Kalachai", provinceId: 25 },
  { id: 379, fa: "هشتپر", en: "Hashtpar", provinceId: 25 },
  { id: 380, fa: "رضوان شهر", en: "Rezvanshahr", provinceId: 25 },
  { id: 381, fa: "ماسال", en: "Masal", provinceId: 25 },
  { id: 382, fa: "شفت", en: "Shaft", provinceId: 25 },
  { id: 383, fa: "سياهكل", en: "Siahkal", provinceId: 25 },
  { id: 384, fa: "املش", en: "Omlesh", provinceId: 25 },
  { id: 385, fa: "لاهیجان", en: "Lahijan", provinceId: 25 },
  { id: 386, fa: "خشک بيجار", en: "Khoshk-e Bijar", provinceId: 25 },
  { id: 387, fa: "خمام", en: "Khomam", provinceId: 25 },
  { id: 388, fa: "لشت نشا", en: "Lasht-e Nesha", provinceId: 25 },
  { id: 389, fa: "بندر کياشهر", en: "Bandar-e Kiashahr", provinceId: 25 },
  { id: 390, fa: "ساري", en: "Sari", provinceId: 26 },
  { id: 391, fa: "آمل", en: "Amol", provinceId: 26 },
  { id: 392, fa: "بابل", en: "Babol", provinceId: 26 },
  { id: 393, fa: "بابلسر", en: "Babolsar", provinceId: 26 },
  { id: 394, fa: "بهشهر", en: "Behshahr", provinceId: 26 },
  { id: 395, fa: "تنكابن", en: "Tonekabon", provinceId: 26 },
  { id: 396, fa: "جويبار", en: "Juybar", provinceId: 26 },
  { id: 397, fa: "چالوس", en: "Chalus", provinceId: 26 },
  { id: 398, fa: "رامسر", en: "Ramsar", provinceId: 26 },
  { id: 399, fa: "سواد كوه", en: "Savad Kouh", provinceId: 26 },
  { id: 400, fa: "قائم شهر", en: "Qaem Shahr", provinceId: 26 },
  { id: 401, fa: "نكا", en: "Neka", provinceId: 26 },
  { id: 402, fa: "نور", en: "Nur", provinceId: 26 },
  { id: 403, fa: "بلده", en: "Baladeh", provinceId: 26 },
  { id: 404, fa: "نوشهر", en: "Nowshahr", provinceId: 26 },
  { id: 405, fa: "پل سفيد", en: "Pol Sefid", provinceId: 26 },
  { id: 406, fa: "محمود آباد", en: "Mahmudabad", provinceId: 26 },
  { id: 407, fa: "فريدون كنار", en: "Fereydunkenar", provinceId: 26 },
  { id: 408, fa: "بندرعباس", en: "Bandar-e Abbas", provinceId: 27 },
  { id: 409, fa: "قشم", en: "Qeshm", provinceId: 27 },
  { id: 410, fa: "كيش", en: "Kish", provinceId: 27 },
  { id: 411, fa: "بندر لنگه", en: "Bandar Lengeh", provinceId: 27 },
  { id: 412, fa: "بستك", en: "Bastak", provinceId: 27 },
  { id: 413, fa: "حاجي آباد", en: "Hajjiabad", provinceId: 27 },
  { id: 414, fa: "دهبارز", en: "Dehbarz", provinceId: 27 },
  { id: 415, fa: "انگهران", en: "Angahran", provinceId: 27 },
  { id: 416, fa: "ميناب", en: "Minab", provinceId: 27 },
  { id: 417, fa: "ابوموسي", en: "Abu Musa", provinceId: 27 },
  { id: 418, fa: "بندر جاسك", en: "Bandar Jask", provinceId: 27 },
  { id: 419, fa: "تنب بزرگ", en: "Tonbe Bozorg", provinceId: 27 },
  { id: 420, fa: "بندر خمیر", en: "Bandar-e Khamir", provinceId: 27 },
  { id: 421, fa: "همدان", en: "Hamadan", provinceId: 28 },
  { id: 422, fa: "ملاير", en: "Malayer", provinceId: 28 },
  { id: 423, fa: "تويسركان", en: "Tuyserkan", provinceId: 28 },
  { id: 424, fa: "نهاوند", en: "Nahavand", provinceId: 28 },
  { id: 425, fa: "كبودر اهنگ", en: "Kabudarahang", provinceId: 28 },
  { id: 426, fa: "رزن", en: "Razan", provinceId: 28 },
  { id: 427, fa: "اسدآباد", en: "Asadabad", provinceId: 28 },
  { id: 428, fa: "بهار", en: "Bahar", provinceId: 28 },
  { id: 429, fa: "یزد", en: "Yazd", provinceId: 29 },
  { id: 430, fa: "تفت", en: "Taft", provinceId: 29 },
  { id: 431, fa: "اردكان", en: "Ardakan", provinceId: 29 },
  { id: 432, fa: "ابركوه", en: "Abarkuh", provinceId: 29 },
  { id: 433, fa: "ميبد", en: "Meybod", provinceId: 29 },
  { id: 434, fa: "طبس", en: "Tabas", provinceId: 29 },
  { id: 435, fa: "بافق", en: "Bafq", provinceId: 29 },
  { id: 436, fa: "مهريز", en: "Mehriz", provinceId: 29 },
  { id: 437, fa: "اشكذر", en: "Ashkezar", provinceId: 29 },
  { id: 438, fa: "هرات", en: "Harat", provinceId: 29 },
  { id: 439, fa: "خضرآباد", en: "Khezrabad", provinceId: 29 },
  { id: 440, fa: "شاهديه", en: "Shahediyeh", provinceId: 29 },
  { id: 441, fa: "حمیدیه شهر", en: "Hamidiyeh Shahr", provinceId: 29 },
  { id: 442, fa: "سید میرزا", en: "Seyed Mirza", provinceId: 29 },
  { id: 443, fa: "زارچ", en: "Zarch", provinceId: 29 },
];
