export const JobCats = [
  { id: 1, fa: "آموزشی", en: "Educational", parentId: null },
  { id: 2, fa: "مدرس زبان", en: "Language teacher", parentId: 1 },
  {
    id: 3,
    fa: "معلم / معلم خصوصی",
    en: "Teacher / tutor teacher",
    parentId: 1,
  },
  {
    id: 4,
    fa: "مشاور کنکور / مشاور تحصیلی",
    en: "Concours Advisor / Academic adviser",
    parentId: 1,
  },
  { id: 5, fa: "مربی آموزش رانندگی", en: "Driving instructor", parentId: 1 },
  ,
  {
    id: 6,
    fa: "مربی باشگاه / مربی ورزشی",
    en: "instructer of the gym / coach",
    parentId: 1,
  },
  {
    id: 7,
    fa: "مربی کودکان / کودکیار",
    en: "Children's coach / childcare",
    parentId: 1,
  },
  { id: 8, fa: "مربی کودکان خاص", en: "Special children's coach", parentId: 1 },
  {
    id: 9,
    fa: "مربی رشته های هنری",
    en: "Instructor of art disciplines",
    parentId: 1,
  },
  { id: 10, fa: "مربی آرایشگری", en: "Hairdressing instructor", parentId: 1 },
  {
    id: 11,
    fa: "مربی صنایع غذایی / قنادی",
    en: "food industry teacher / Confectionery instructor",
    parentId: 1,
  },
  {
    id: 12,
    fa: "مربی آموزش هتلداری / گردشگری",
    en: " Tourism / Hotel training instructor",
    parentId: 1,
  },
  { id: 13, fa: "مربی کافی من", en: "Coffeman instructor", parentId: 1 },
  {
    id: 14,
    fa: "مربی تعمیرات خودرو",
    en: "Car repair instructor",
    parentId: 1,
  },
  {
    id: 15,
    fa: "مربی تعمیرات کامپیوتر و لپ تاپ",
    en: "Computer and laptop repair instructor",
    parentId: 1,
  },
  {
    id: 16,
    fa: "مربی برق مکانیک",
    en: "Electrical-Mechanical Instructor",
    parentId: 1,
  },
  {
    id: 17,
    fa: "مربی تعمیرات لوازم خانگی",
    en: "Home Appliance Repair Instructor",
    parentId: 1,
  },
  {
    id: 18,
    fa: "مربی برق ساختمان",
    en: "Building electrical instructor",
    parentId: 1,
  },
  { id: 19, fa: "مربی فناوری اطلاعات", en: "IT coach", parentId: 1 },
  {
    id: 20,
    fa: "مدرس بازارهای مالی",
    en: "Financial Markets Instructor",
    parentId: 1,
  },
  {
    id: 21,
    fa: "مربی استراتژی های بازاریابی",
    en: "Instructor of marketing strategies",
    parentId: 1,
  },
  { id: 22, fa: "مربی پرواز", en: "Flight instructor", parentId: 1 },
  { id: 23, fa: "مربی فن بیان", en: "Speech instructor", parentId: 1 },
  {
    id: 24,
    fa: "اداری / مالی",
    en: "administrative and financial",
    parentId: null,
  },
  ,
  { id: 25, fa: "حسابدار", en: "Accountants", parentId: 24 },
  {
    id: 26,
    fa: "منشی / منشی مطب",
    en: "the Secretary / Secretary's office",
    parentId: 24,
  },
  {
    id: 27,
    fa: "منشی مدیر عامل / مسئول دفتر",
    en: "Secretary General / Office Manager",
    parentId: 24,
  },
  { id: 28, fa: "مسئول پذیرش", en: "receptionist", parentId: 24 },
  { id: 29, fa: "تایپیست", en: "Typist", parentId: 24 },
  { id: 30, fa: "صندوق دار", en: "Cashier", parentId: 24 },
  {
    id: 31,
    fa: "کارمند آژانس مسافرتی",
    en: "Travel agency employee",
    parentId: 24,
  },
  {
    id: 32,
    fa: "کارمند آشنا به زبان انگلیسی",
    en: "Employee with acquaintance English ",
    parentId: 24,
  },
  {
    id: 33,
    fa: "کارشناس وصول مطالبات / کارپرداز",
    en: "Claims Collection Expert / Supplier",
    parentId: 24,
  },
  {
    id: 34,
    fa: "کارمند منابع انسانی",
    en: "Human Resources Officer",
    parentId: 24,
  },
  {
    id: 35,
    fa: "کارمند روابط عمومی",
    en: "Public Relations Officer",
    parentId: 24,
  },
  {
    id: 36,
    fa: "مدیریت / مدیر عامل / معاونت",
    en: "Management / Managing Director / Vice President",
    parentId: 24,
  },
  {
    id: 37,
    fa: "تحلیل گر بازارهای مالی / تحلیلگر بورس",
    en: "Financial Market Analyst / Stock market Analyst",
    parentId: 24,
  },
  {
    id: 38,
    fa: " بازاریابی و فروش",
    en: "Marketing and sales",
    parentId: null,
  },
  {
    id: 39,
    fa: "مدیر بازاریابی / مدیر فروش / مدیر مارکتینگ",
    en: "Marketing Manager / Sales Manager / Marketing Manager",
    parentId: 38,
  },
  {
    id: 40,
    fa: "کارشناس فروش / کارشناس بازاریابی / کارشناس برندینگ",
    en: "Sales Expert / Marketing Expert / Branding Expert",
    parentId: 38,
  },
  {
    id: 41,
    fa: "بازاریاب و ویزیتور",
    en: "Marketer and Visitor",
    parentId: 38,
  },
  {
    id: 42,
    fa: "کارمند فروش / منشی فروش",
    en: "Sales clerk / sales secretary",
    parentId: 38,
  },
  { id: 43, fa: "فروشنده", en: "the seller", parentId: 38 },
  { id: 44, fa: "کارشناس تبلیغات", en: "Advertising expert", parentId: 38 },
  {
    id: 45,
    fa: "مدیر بازرگانی / کارشناس بازرگانی",
    en: "Business Manager / Business Expert",
    parentId: 38,
  },
  { id: 46, fa: "تحلیلگر بازار", en: "Market Analyst", parentId: 38 },
  {
    id: 47,
    fa: "مدیر توسعه بازار",
    en: "Market Development Manager",
    parentId: 38,
  },
  { id: 48, fa: "خدمات", en: "Services", parentId: null },
  ,
  { id: 49, fa: "کارگر", en: "manual worker", parentId: 48 },
  { id: 50, fa: "کارگر رستوران", en: "Restaurant worker", parentId: 49 },
  { id: 51, fa: "کارگر ساده", en: "worker", parentId: 49 },
  {
    id: 52,
    fa: "کارگر انبار / انباردار",
    en: "Warehouse worker / warehouseman",
    parentId: 49,
  },
  { id: 53, fa: "سرایدار", en: "Janitor", parentId: 49 },
  { id: 54, fa: "پارکبان", en: "Park Guard", parentId: 49 },
  { id: 55, fa: "نصاب", en: "Installer", parentId: 49 },
  { id: 56, fa: "مونتاژکار", en: "Assemblyman", parentId: 49 },
  {
    id: 57,
    fa: "کارگر رستوران/ کارگر هتل",
    en: "Restaurant worker / hotel worker",
    parentId: 49,
  },
  { id: 58, fa: "اپراتور دستگاه", en: "Device operator", parentId: 49 },
  { id: 59, fa: "کارگر کارواش", en: "Carwash worker", parentId: 49 },
  { id: 60, fa: "آبدارچی و کارگر نظافت", en: "Carwash worker", parentId: 49 },
  { id: 61, fa: "کارگر ماهر / نیمه ماهر", en: "", parentId: 48 },
  { id: 62, fa: "تراشکار", en: "turner", parentId: 61 },
  { id: 63, fa: "CNC کار", en: "CNC worker", parentId: 61 },
  { id: 64, fa: "جوشکار", en: "Welder", parentId: 61 },
  { id: 65, fa: "فرزکار", en: "Milling", parentId: 61 },
  { id: 66, fa: "برق کار", en: "electrician", parentId: 61 },
  {
    id: 67,
    fa: "قالبساز / تزریق کار پلاستیک",
    en: "Mold maker / plastic injection work",
    parentId: 61,
  },
  {
    id: 68,
    fa: "ورق کار / MDF کار",
    en: "Sheet work / MDF work",
    parentId: 61,
  },
  { id: 69, fa: "کابینت ساز", en: "cabinet maker", parentId: 61 },
  { id: 70, fa: "نجار", en: "Carpenter", parentId: 61 },
  { id: 71, fa: "طلاساز", en: "Goldsmith", parentId: 61 },
  { id: 72, fa: "آهنگر", en: "blacksmith", parentId: 61 },
  { id: 73, fa: "نانوا", en: "Baker", parentId: 61 },
  { id: 74, fa: "پرس کار", en: "Press work", parentId: 61 },
  { id: 75, fa: "فلزکار", en: "metal working", parentId: 61 },
  { id: 76, fa: "مبل ساز", en: "Cabinet-maker", parentId: 61 },
  { id: 77, fa: "شیشه بر", en: "Glazier", parentId: 61 },
  { id: 78, fa: "بنا", en: "masonry", parentId: 61 },
  { id: 79, fa: "قصاب", en: "Butcher", parentId: 61 },
  { id: 80, fa: "کاشی‌کار", en: "Tiling", parentId: 61 },
  { id: 81, fa: "کناف کار", en: "Knaf work", parentId: 61 },
  { id: 82, fa: "گچ‌ کار", en: "Plaster work", parentId: 61 },
  { id: 83, fa: "لوله کش", en: "Plumber", parentId: 61 },
  { id: 84, fa: "نقاش ساختمان", en: "Building Painter", parentId: 61 },
  {
    id: 85,
    fa: "کارگر ساختمانی / عمله",
    en: "construction worker",
    parentId: 61,
  },
  { id: 86, fa: "خیاط", en: "Tailor", parentId: 61 },
  {
    id: 87,
    fa: "مشاغل خانگی / صنایع دستی",
    en: "Homework / Crafts",
    parentId: 48,
  },
  {
    id: 88,
    fa: "قالیبافی / بافندگی",
    en: "Carpet weaving / weaving",
    parentId: 87,
  },
  {
    id: 89,
    fa: "نقاشی / میناکاری / قلمزنی",
    en: "Painting / Enameling / Engraving",
    parentId: 87,
  },
  { id: 90, fa: "امور تولیدی", en: "Production affairs", parentId: 87 },
  { id: 91, fa: "امور بسته بندی", en: "Packaging affairs", parentId: 87 },
  {
    id: 92,
    fa: "سایر فعالیت های فرهنگی هنری",
    en: "Other cultural and artistic activities",
    parentId: 87,
  },

  { id: 93, fa: "خدمات وسایل نقلیه", en: "Vehicle services", parentId: 48 },
  { id: 94, fa: "تعمیرات", en: "Repairs", parentId: 93 },
  {
    id: 95,
    fa: "تزئینات و تیونینگ",
    en: "Decorating and tuning",
    parentId: 93,
  },
  { id: 96, fa: "سرویس خودرو", en: "Car service", parentId: 93 },
  {
    id: 97,
    fa: "جرثقیل و امدادخودرو",
    en: "Crane and ambulance",
    parentId: 93,
  },
  {
    id: 98,
    fa: "صافکاری و نقاشی",
    en: "Refinement and painting",
    parentId: 93,
  },

  { id: 99, fa: "خدمات ساختمانی", en: "Building services", parentId: 48 },
  { id: 100, fa: "تأسیساتی", en: "Installation", parentId: 99 },
  {
    id: 101,
    fa: "طراح داخلی و دکوراسیون",
    en: "Interior and decoration designer",
    parentId: 99,
  },
  {
    id: 102,
    fa: "عمرانی، معماری و بنایی",
    en: "Civil engineering, architecture and construction",
    parentId: 99,
  },
  {
    id: 103,
    fa: "سایر خدمات ساختمانی",
    en: "Other construction services",
    parentId: 99,
  },

  {
    id: 104,
    fa: "کلینیک زیبایی / سالن زیبایی",
    en: "Beauty Clinic / Beauty Salon",
    parentId: 48,
  },
  { id: 105, fa: "آرایشگر مردانه", en: "Men's hairdresser", parentId: 104 },
  { id: 106, fa: "آرایشگر زنانه", en: "women hairdressing", parentId: 104 },
  {
    id: 107,
    fa: "وردست آرایشگر / کمک آرایشگر / دستیار آرایشگر",
    en: "Hairdresser Assistant",
    parentId: 104,
  },
  { id: 108, fa: "کراتین کار مو", en: "Creatine hair work", parentId: 104 },
  {
    id: 109,
    fa: "اسکین کر / پوست کار /  فیشیالیست",
    en: "Skinner / Dermatologist / Facialist",
    parentId: 104,
  },
  { id: 110, fa: "میکاپ کار", en: "Make-up work", parentId: 104 },
  { id: 111, fa: "شنیون کار", en: "chignon work", parentId: 104 },
  {
    id: 112,
    fa: "اکستنشن کار مو و مژه",
    en: "Hair and eyelash extensions",
    parentId: 104,
  },
  { id: 113, fa: "ناخن کار", en: "nail specialist", parentId: 104 },
  {
    id: 114,
    fa: "کوپ کار و براشینگ کار",
    en: "Cutting work and brushing work",
    parentId: 104,
  },
  { id: 115, fa: "اپیلاسیون کار", en: "Waxing work", parentId: 104 },
  { id: 116, fa: " ابرو کار / اصلاح کار", en: "Eyebrow work", parentId: 104 },
  {
    id: 117,
    fa: "رنگ و مش کار",
    en: "Hair color and mesh work",
    parentId: 104,
  },
  { id: 118, fa: "تاتو کار", en: "", parentId: 104 },
  { id: 119, fa: "", en: "Tattoo work", parentId: 104 },

  {
    id: 120,
    fa: "اپراتور / کارمند بازنشسته",
    en: "Retired employee / operator ",
    parentId: 48,
  },
  {
    id: 121,
    fa: "نیروی خدماتی باغ / تالار / فروشگاه",
    en: "Garden / Hall / Store Service Force",
    parentId: 48,
  },
  {
    id: 122,
    fa: "خرید و تدارکات",
    en: "Purchasing and logistics",
    parentId: 48,
  },
  { id: 123, fa: "خدمات مجالس/مراسم", en: "Party services", parentId: 48 },
  {
    id: 124,
    fa: "همیاران کودک و سالمند",
    en: "Child and elderly helpers",
    parentId: 48,
  },
  { id: 125, fa: "راننده / باربری", en: "Driver / Freight", parentId: 48 },
  {
    id: 126,
    fa: "پیک و تحویل دهنده / پیک موتوری",
    en: "Courier and delivery / motor courier",
    parentId: 48,
  },
  {
    id: 127,
    fa: "نگهبان / انتظامات / حراست",
    en: "Guard / Arrangement",
    parentId: 48,
  },
  { id: 128, fa: "قناد / شیرینی پز", en: "Confectionery", parentId: 48 },
  { id: 129, fa: "آشپز/ کمک آشپز", en: "Chef / Assistant Chef", parentId: 48 },
  { id: 130, fa: "گارسون", en: "Waiter", parentId: 48 },
  { id: 131, fa: "باریستا", en: "Barista", parentId: 48 },
  { id: 132, fa: "غواص و غریق نجات", en: "Diver and lifeguard", parentId: 48 },
  { id: 133, fa: "آتش نشان", en: "Firefighters", parentId: 48 },
  { id: 134, fa: "مهماندار هواپیما", en: "Stewardess", parentId: 48 },
  { id: 135, fa: "مترجم زبان", en: "translator", parentId: 48 },
  {
    id: 136,
    fa: " صحاف چاپ و تبلیغات",
    en: "Binding printing and advertising",
    parentId: 48,
  },
  {
    id: 137,
    fa: "تعمیرات سخت افزار و نرم افزار لپ تاپ و کامپیوتر",
    en: "Binding printing and advertising",
    parentId: 48,
  },
  {
    id: 138,
    fa: "تعمیرات لوازم خانگی و لوازم برقی",
    en: "Appliance and electrical appliance repairs",
    parentId: 48,
  },
  { id: 139, fa: "تعمیر کار آسانسور", en: "Elevator repairman", parentId: 48 },
  { id: 140, fa: "طراح فرش", en: "carpet designer", parentId: 48 },
  { id: 141, fa: "طراح طلا و جواهر", en: "Jewelry designer", parentId: 48 },
  { id: 142, fa: "ماساژور / ماسور", en: "Massager", parentId: 48 },

  {
    id: 143,
    fa: "کشاورزی و محیط زیست",
    en: "Agriculture and Environment",
    parentId: null,
  },
  ,
  {
    id: 144,
    fa: "مهندس کشاورزی / کارشناس کشاورزی",
    en: "Agricultural Engineer / Agricultural Expert",
    parentId: 143,
  },
  {
    id: 145,
    fa: "باغبانی و درختکاری",
    en: "Horticulture and arboriculture",
    parentId: 143,
  },
  {
    id: 146,
    fa: "کارشناس شیلات و آبزیان",
    en: "Fisheries and Aquatic Expert",
    parentId: 143,
  },
  { id: 147, fa: "دامپزشک", en: "Vet", parentId: 143 },

  { id: 148, fa: "فنی مهندسی", en: "Engineering", parentId: null },
  ,
  {
    id: 149,
    fa: "مهندس عمران / نقشه کشی صنعتی",
    en: "Civil Engineer / Industrial Drawing",
    parentId: 148,
  },
  { id: 150, fa: "مهندس مکانیک", en: "mechanical engineer", parentId: 148 },
  { id: 151, fa: "مهندس برق‏", en: "Electrical Engineer", parentId: 148 },
  {
    id: 152,
    fa: "مهندس صنایع‏ غذایی",
    en: "Food Industry Engineer",
    parentId: 148,
  },
  {
    id: 153,
    fa: "مهندس شیمی / نفت / پلیمر",
    en: "Chemical / Petroleum / Polymer Engineer",
    parentId: 148,
  },
  {
    id: 154,
    fa: "مهندس معدن / زمین شناس",
    en: "Mining Engineer / Geologist",
    parentId: 148,
  },
  {
    id: 155,
    fa: "مهندس معماری و شهر سازی",
    en: "Architect and Urban Planning Engineer",
    parentId: 148,
  },
  {
    id: 156,
    fa: "مهندس مواد و متالورژی",
    en: "Materials and Metallurgy Engineer",
    parentId: 148,
  },
  { id: 157, fa: "مهندس نساجی‏", en: "Textile Engineer", parentId: 148 },
  { id: 158, fa: "مهندس پزشکی", en: "Medical Engineering", parentId: 148 },
  {
    id: 159,
    fa: "مهندس مخابرات",
    en: "Telecommunications Engineer",
    parentId: 148,
  },
  { id: 160, fa: "مهندس رباتیک", en: "Robotics Engineer", parentId: 148 },
  { id: 161, fa: "مهندس هوافضا‏", en: "Aerospace Engineer", parentId: 148 },
  {
    id: 162,
    fa: "مهندس اپتیک و لیزر‏",
    en: "Optics and Laser Engineer",
    parentId: 148,
  },
  { id: 163, fa: "مهندس انرژی‏", en: "Energy Engineer", parentId: 148 },
  { id: 164, fa: "تکنسین فنی", en: "technician", parentId: 148 },
  {
    id: 165,
    fa: "مدیر محصول / مدیر توسعه محصول / مدیر کنترل کیفی / مدیر پروژه",
    en: "Product Manager / Product Development Manager / Quality Control Manager / Project Manager",
    parentId: 148,
  },
  {
    id: 166,
    fa: "مدیر کنترل کیفیت / کارشناس کنترل کیفیت",
    en: "Quality Control Manager / Quality Control Expert",
    parentId: 148,
  },

  {
    id: 167,
    fa: "فناوری اطلاعات",
    en: "Information Technology",
    parentId: null,
  },
  ,
  { id: 168, fa: "برنامه نویس و دولوپر", en: "Developer", parentId: 167 },
  { id: 169, fa: "مهندس نرم افزار", en: "Software Engineer", parentId: 167 },
  { id: 170, fa: "طراح وب سایت", en: "Web designer", parentId: 167 },
  {
    id: 171,
    fa: "کارشناس تولید محتوا",
    en: "Content production expert",
    parentId: 167,
  },
  {
    id: 172,
    fa: "مدیر وب سایت / پشتیبان سایت",
    en: "Webmaster / Site Supporter",
    parentId: 167,
  },
  { id: 173, fa: "کارشناس سئو SEO", en: "SEO expert", parentId: 167 },
  { id: 174, fa: "طراح UI/UX", en: "UI / UX designer", parentId: 167 },
  {
    id: 175,
    fa: "کارشناس دیجیتال مارکتینگ",
    en: "Digital Marketing Expert",
    parentId: 167,
  },
  {
    id: 176,
    fa: "کارشناس پشتیبانی فنی هاست و دامین",
    en: "Host and domain technical support expert",
    parentId: 167,
  },
  { id: 177, fa: "کارشناس SysAdmin", en: "SysAdmin Expert", parentId: 167 },
  {
    id: 178,
    fa: "کارشناس دیتاسنتر و مجازی سازی",
    en: "Expert in data center and virtualization",
    parentId: 167,
  },
  {
    id: 179,
    fa: "کارشناس امنیت و مدیریت شبکه",
    en: "Network Security and Management Expert",
    parentId: 167,
  },
  {
    id: 180,
    fa: "کارشناس فناوری اطلاعات (IT)",
    en: "Information Technology (IT) Expert",
    parentId: 167,
  },
  { id: 181, fa: "طراح گرافیست", en: "Graphic designer", parentId: 167 },
  {
    id: 182,
    fa: "کارشناس انیمیشن ساز و انیماتور / طراح تیزر",
    en: "Animation expert and animator / teaser designer",
    parentId: 167,
  },
  { id: 183, fa: "مهندس سخت افزار", en: "Hardware Engineer", parentId: 167 },
  {
    id: 184,
    fa: "پشتیبان سخت افزار و تجهیزات کامپیوتری",
    en: "Backup of computer hardware and equipment",
    parentId: 167,
  },
  {
    id: 185,
    fa: "ادمین شبکه های اجتماعی",
    en: "Social Network Admin",
    parentId: 167,
  },
  {
    id: 186,
    fa: "طراح 3D / طراح دو بعدی",
    en: "3D Designer / 2D Designer",
    parentId: 167,
  },
  { id: 187, fa: "پشتیبان نرم‌افزار", en: "Software support", parentId: 167 },
  { id: 188, fa: "کارشناس شبکه", en: "Network expert", parentId: 167 },
  {
    id: 189,
    fa: "کارشناس بانک اطلاعاتی (متخصص پایگاه داده)",
    en: "Database Expert (Database Specialist)",
    parentId: 167,
  },
  {
    id: 190,
    fa: "مدیر پروژه نرم افزار",
    en: "Software project manager",
    parentId: 167,
  },
  {
    id: 191,
    fa: "کارشناس هوش مصنوعی",
    en: "Artificial intelligence expert",
    parentId: 167,
  },

  {
    id: 192,
    fa: "پزشکی / بهداشتی / درمانی",
    en: "Medical / Health / Therapeutic",
    parentId: null,
  },
  ,
  {
    id: 193,
    fa: "روانشناس / روانپزشک / مشاور",
    en: "Psychologist / Psychiatrist / Counselor",
    parentId: 192,
  },
  {
    id: 194,
    fa: "دستیار دندانپزشک / دستیار پزشک",
    en: "Dentist Assistant / Physician Assistant",
    parentId: 192,
  },
  {
    id: 195,
    fa: "پرستار / ماما / بهیار / امدادگر / مددکار",
    en: "Nurse / Midwife / Relief / Assistant",
    parentId: 192,
  },
  {
    id: 196,
    fa: "پزشک عمومی / پزشک متخصص",
    en: "General Practitioner / Specialist Physician",
    parentId: 192,
  },
  {
    id: 197,
    fa: "کارشناس علوم آزمایشگاهی / کارشناس علوم زیستی",
    en: "Laboratory Science Expert / Biological Science Expert",
    parentId: 192,
  },
  {
    id: 198,
    fa: "فیزیوتراپیست / رادیولوژیست",
    en: "Physiotherapist / radiologist",
    parentId: 192,
  },
  {
    id: 199,
    fa: "تکنسین / اپراتور",
    en: "Technician / Operator",
    parentId: 192,
  },
];
