export const SalaryType = [
  { id: 1, fa: "ماهانه", en: "" },
  { id: 2, fa: "روزانه", en: "" },
  { id: 3, fa: "ساعتی", en: "" },
  { id: 4, fa: "پورسانتی", en: "" },
  { id: 5, fa: "توافقی", en: "" },
];

export const corporateTime = [
  { id: 1, fa: "تمام وقت", en: "" },
  { id: 2, fa: "پاره وقت", en: "" },
  { id: 3, fa: "پروژه ای", en: "" },
  { id: 4, fa: "کارآموزی", en: "" },
  { id: 5, fa: "توافقی", en: "" },
];
export const sex = [
  { id: 1, fa: "مرد", en: "" },
  { id: 2, fa: " زن", en: "" },
  { id: 3, fa: "مهم نیست", en: "" },
   
];

export const Langsfa=[
  {id: 1 ,name: 'فارسی'},
  {id: 1 ,name: 'انگلیسی'},
  {id: 1 ,name: 'عربی'},
  {id: 1 ,name: 'فرانسوی '},
  {id: 1 ,name: 'آلمانی'},
  {id: 1 ,name: 'اسپانیایی'},
  {id: 1 ,name: 'ایتالیایی'},
  {id: 1 ,name: 'ترکی'},
  {id: 1 ,name: 'پرتغالی'},
  {id: 1 ,name: 'ژاپنی'},
  {id: 1 ,name: 'کره ای'},
  {id: 1 ,name: 'چینی'},
  {id: 1 ,name: 'ارمنی'},
  {id: 1 ,name: 'یونانی'},
  {id: 1 ,name: 'هندی'},
  {id: 1 ,name: 'کوردی'},
]
export const Langsen=[
  {id: 1 ,name: 'Persian'},
  {id: 1 ,name: 'English'},
  {id: 1 ,name: 'Arabic'},
  {id: 1 ,name: 'French'},
  {id: 1 ,name: 'German'},
  {id: 1 ,name: 'Spanish'},
  {id: 1 ,name: 'Italian'},
  {id: 1 ,name: 'Russian'},
  {id: 1 ,name: 'Turkish'},
  {id: 1 ,name: 'Portuguese'},
  {id: 1 ,name: 'Japanese'},
  {id: 1 ,name: 'Korean'},
  {id: 1 ,name: 'Chinese '},
  {id: 1 ,name: 'Armenian '},
  {id: 1 ,name: 'Greek '},
  {id: 1 ,name: 'Hindi '},
  {id: 1 ,name: 'Kurdish '},
  
]
 
export const Softs=[
{id: 1 , fa:"نرم افزارها و زبان های برنامه نویسی" , en:"Software and programming languages" ,parentId:null },
{id: 2 , fa:"سوییفت" , en:"Swift" ,parentId : 1 },
{id: 3 , fa:"مایکروسافت ویژوال استودیو" , en:"Microsoft Visual Studio" ,parentId : 1 },
{id: 4 , fa:"اکلیپس" , en:"Eclipse" ,parentId : 1 },
{id: 5 , fa:"نت بینز" , en:"Netbeans" ,parentId : 1 },
{id: 6 , fa:"اندروید استودیو" , en:"Android Studio" ,parentId : 1 },
{id: 7 , fa:"نوت پد پلاس پلاس" , en:"Notepad++" ,parentId : 1 },
{id: 8 , fa:"سی شارپ" , en:"C#" ,parentId : 1 },
{id: 9 , fa:"سی پلاس پلاس" , en:"C++" ,parentId : 1 },
{id: 10 , fa:"جاوا" , en:"Java" ,parentId : 1 },
{id: 11 , fa:"سی" , en:"C" ,parentId : 1 },
{id: 12 , fa:"دلفی" , en:"Delphi" ,parentId : 1 },
{id: 13 , fa:"پاسکال" , en:"Pascal" ,parentId : 1 },
{id: 14 , fa:"روبی آن ریلز" , en:"Ruby on Rails" ,parentId : 1 },
{id: 15 , fa:"پایتون" , en:"Python" ,parentId : 1 },
{id: 16 , fa:"ای اس پی دات نت" , en:"ASP.Net" ,parentId : 1 },
{id: 17 , fa:"اس پی دات نت ام وی سی" , en:"ASP.Net MVC" ,parentId : 1 },
{id: 18 , fa:"ام وی سی" , en:"MVC" ,parentId : 1 },
{id: 19 , fa:"تی اف اس" , en:"TFS (Team Foundation Server)" ,parentId : 1 },
{id: 20 , fa:"اچ تی ام ال و سی اس اس" , en:"Html & CSS" ,parentId : 1 },
{id: 21 , fa:"جاوا اسکریپت" , en:"JavaScript" ,parentId : 1 },
{id: 22 , fa:"وی بی اسکریپت" , en:"VB Script" ,parentId : 1 },
{id: 23 , fa:"گو" , en:"Go" ,parentId : 1 },
{id: 24 , fa:"برنامه نویسی اندروید" , en:"Android Development" ,parentId : 1 },
{id: 25 , fa:"پی اچ پی" , en:"PHP" ,parentId : 1 },
{id: 26 , fa:"تی اس کیو ال" , en:"T-Sql" ,parentId : 1 },
{id: 27 , fa:"نود جی اس" , en:"Node.js" ,parentId : 1 },
{id: 28 , fa:"جی کوئری" , en:"JQuery" ,parentId : 1 },
{id: 29 , fa:"فرترن" , en:"Fortran" ,parentId : 1 },
{id: 30 , fa:"اسمبلی" , en:"Assembly" ,parentId : 1 },
{id: 31 , fa:"زامارین" , en:"Xamarin" ,parentId : 1 },
{id: 32 , fa:"برنامه نویسی آی او اس" , en:"iOS Development (Objective C)" ,parentId : 1 },
{id: 33 , fa:"ویژوال بیسیک" , en:"Visual Basic" ,parentId : 1 },
{id: 34 , fa:"کریستال ریپورت" , en:"Crystal Reports" ,parentId : 1 },
{id: 35 , fa:"بستر گزارشگری مایکروسافت" , en:"Microsoft Reporting Services" ,parentId : 1 },
{id: 36 , fa:"بستر آنالیز مایکروسافت" , en:"Microsoft Analysis Services" ,parentId : 1 },
{id: 37 , fa:"نرم افزار گزارش گیری استیمول سافت" , en:"Stimulsoft Report" ,parentId : 1 },
{id: 38 , fa:"گزارش گر فست ریپورت" , en:"Fast Report" ,parentId : 1 },
{id: 39 , fa:"گزارش گر کوییک ریپورت" , en:"Quick Report" ,parentId : 1 },
{id: 40 , fa:"ساب ورژن" , en:"Subversion" ,parentId : 1 },
{id: 41 , fa:"گیت" , en:"GIT" ,parentId : 1 },
{id: 42 , fa:"اکس کد" , en:"Xcode" ,parentId : 1 },
{id: 43 , fa:"آنگولار" , en:"Angular" ,parentId : 1 },
{id: 44 , fa:"جنگو" , en:"Django" ,parentId : 1 },
{id: 45 , fa:"لاراول" , en:"Laravel" ,parentId : 1 },
{id: 46 , fa:"هایبرنت" , en:"Hibernate" ,parentId : 1 },
{id: 47 , fa:"رستفول ای پی آی" , en:"Rest API" ,parentId : 1 },
{id: 48 , fa:"ری اکت" , en:"React" ,parentId : 1 },
{id: 49 , fa:"یونیت تست" , en:"Unit Testing" ,parentId : 1 },
{id: 50 , fa:"تزریق وابستگی" , en:"Dependency Injection" ,parentId : 1 },
{id: 51 , fa:"انتیتی فریم ورک" , en:"Entity Framework" ,parentId : 1 },
{id: 52 , fa:"ویژوال پارادایم" , en:"Visual Paradigm" ,parentId : 1 },
{id: 53 , fa:"رشنال رز" , en:"Rational rose" ,parentId : 1 },
{id: 54 , fa:"سلنیوم" , en:"Selenium" ,parentId : 1 },
{id: 55 , fa:"جنکینز" , en:"Jenkins" ,parentId : 1 },
{id: 56 , fa:"گوگل آنالیتیکس" , en:"Google Analytics" ,parentId : 1 },
{id: 57 , fa:"مایکروسافت تست منیجر" , en:"Microsoft Test Manager" ,parentId : 1 },
{id: 58 , fa:"کافکا" , en:"Kafka" ,parentId : 1 },
{id: 59 , fa:"زیرو ام کیو" , en:"ZeroMQ" ,parentId : 1 },
{id: 60 , fa:"الاستیک سرچ" , en:"Elastic Search" ,parentId : 1 },
{id: 61 , fa:"جیرا" , en:"Jira" ,parentId : 1 },
{id: 62 , fa:"ویو جی اس" , en:"VueJS" ,parentId : 1 },
{id: 63 , fa:"اوپن سی وی" , en:"OpenCV" ,parentId : 1 },
{id: 64 , fa:"کرس" , en:"Keras" ,parentId : 1 },
{id: 65 , fa:"پی‌ ال / اس‌ کیو ال" , en:"PL-SQL" ,parentId : 1 },
{id: 66 , fa:"دات نت" , en:".NET" ,parentId : 1 },
{id: 67 , fa:"جاوا اس ای" , en:"Java SE" ,parentId : 1 },
{id: 68 , fa:"اوراکل وبلاجیک" , en:"Oracle WebLogic" ,parentId : 1 },
{id: 69 , fa:"اوراکل فرم" , en:"Oracle Form & Report" ,parentId : 1 },
{id: 70 , fa:"ری اکت نیتیو" , en:"React Native" ,parentId : 1 },
{id: 71 , fa:"دارت" , en:"Dart" ,parentId : 1 },
{id: 72 , fa:"فلاتر" , en:"Flutter" ,parentId : 1 },
{id: 73 , fa:"دات نت کر" , en:".Net Core" ,parentId : 1 },
{id: 74 , fa:"امبدد سی" , en:"Embedded C" ,parentId : 1 },
{id: 75 , fa:"مایکروسافت آژور دواپس" , en:"Microsoft Azure Devops" ,parentId : 1 },
{id: 76 , fa:"دپر" , en:"Dapper" ,parentId : 1 },
{id: 77 , fa:"کاتلین" , en:"Kotlin" ,parentId : 1 },
{id: 78 , fa:"تایپ اسکریپت" , en:"TypeScript" ,parentId : 1 },
{id: 79 , fa:"اسکالا" , en:"Scala" ,parentId : 1 },
{id: 80 , fa:"شل اسکریپت" , en:"ShellScript" ,parentId : 1 },
{id: 81 , fa:"ارلنگ" , en:"Erlang" ,parentId : 1 },
{id: 82 , fa:"گرووی" , en:"Groovy" ,parentId : 1 },
{id: 83 , fa:"راست" , en:"Rust" ,parentId : 1 },
{id: 84 , fa:"الیکسر" , en:"Elixir" ,parentId : 1 },
{id: 85 , fa:"ام کیو ال 4" , en:"MQL4" ,parentId : 1 },
{id: 86 , fa:"ام کیو ال 5" , en:"MQL5" ,parentId : 1 },
{id: 87 , fa:"نکست جی اس" , en:"Next.js" ,parentId : 1 },
{id: 88 , fa:"ناکست جی اس" , en:"Nuxt.js" ,parentId : 1 },
{id: 89 , fa:"نرم افزارهای آفیس" , en:"Office software" ,parentId:null },
{id: 90 , fa:"مایکروسافت ورد" , en:"Microsoft Word" ,parentId : 89 },
{id: 91 , fa:"مایکروسافت اکسل" , en:"Microsoft Excel" ,parentId : 89 },
{id: 92 , fa:"مایکروسافت اکسس" , en:"Microsoft Access" ,parentId : 89 },
{id: 93 , fa:"مایکروسافت پاورپوینت" , en:"Microsoft Powerpoint" ,parentId : 89 },
{id: 94 , fa:"مایکروسافت ویژو" , en:"Microsoft Visio" ,parentId : 89 },
{id: 95 , fa:"مایکروسافت پروجکت" , en:"Microsoft Project" ,parentId : 89 },
{id: 96 , fa:"مایکروسافت وان نوت" , en:"Microsoft One Note" ,parentId : 89 },
{id: 97 , fa:"مایکروسافت آوت لوک" , en:"Microsoft Outlook" ,parentId : 89 },
{id: 98 , fa:"مث تایپ" , en:"MathType" ,parentId : 89 },
{id: 99 , fa:"نرم افزارهای گرافیکی" , en:"Graphic software" ,parentId:null },
{id: 100 , fa:"تری دی مکس" , en:"3D Studio Max" ,parentId : 99 },
{id: 101 , fa:"ای سی دی سی" , en:"ACD See" ,parentId : 99 },
{id: 102 , fa:"ادوبی دریم ویور" , en:"Adobe Dreamweaver" ,parentId : 99 },
{id: 103 , fa:"ادوبی فلش" , en:"Adobe Flash" ,parentId : 99 },
{id: 104 , fa:"ادوبی ایلاستریتور" , en:"Adobe Illustrator" ,parentId : 99 },
{id: 105 , fa:"ادوبی ایندیزاین" , en:"Adobe Indesign" ,parentId : 99 },
{id: 106 , fa:"ادوبی فتوشاپ" , en:"Adobe Photoshop" ,parentId : 99 },
{id: 107 , fa:"ادوبی پریمیر" , en:"Adobe Premiere" ,parentId : 99 },
{id: 108 , fa:"افتر افکت" , en:"After Effects" ,parentId : 99 },
{id: 109 , fa:"آرت ریج" , en:"ArtRage" ,parentId : 99 },
{id: 110 , fa:"بلندر" , en:"Blender" ,parentId : 99 },
{id: 111 , fa:"نرم افزار طراحی 3 بعدی" , en:"Cinema 4D" ,parentId : 99 },
{id: 112 , fa:"کورل دراو" , en:"Corel Draw" ,parentId : 99 },
{id: 113 , fa:"دراو پلاس" , en:"DrawPlus" ,parentId : 99 },
{id: 114 , fa:"گیمپ" , en:"Gimp" ,parentId : 99 },
{id: 115 , fa:"اینسکیپ" , en:"Inkscape" ,parentId : 99 },
{id: 116 , fa:"مایا" , en:"Maya" ,parentId : 99 },
{id: 117 , fa:"فوتو دایرکتور" , en:"PhotoDirector" ,parentId : 99 },
{id: 118 , fa:"فوتو پلاس" , en:"PhotoPlus" ,parentId : 99 },
{id: 119 , fa:"فوتو استودیو" , en:"PhotoStudio" ,parentId : 99 },
{id: 120 , fa:"زارا فوتو و گرافیک دیزاینر" , en:"Xara Photo & Graphic Designer" ,parentId : 99 },
{id: 121 , fa:"تون بوم استودیو" , en:"Toon Boom Studio" ,parentId : 99 },
{id: 122 , fa:"تی وی پینت" , en:"TV Paint" ,parentId : 99 },
{id: 123 , fa:"ادوبی ایکس دی" , en:"Adobe XD" ,parentId : 99 },
{id: 124 , fa:"زیبراش" , en:"ZBrush" ,parentId : 99 },
{id: 125 , fa:"زپلین" , en:"Zeplin" ,parentId : 99 },
{id: 126 , fa:"اسکچ" , en:"Sketch" ,parentId : 99 },
{id: 127 , fa:"آکسور" , en:"Axure" ,parentId : 99 },
{id: 128 , fa:"ادوبی آدیشن" , en:"Adobe Audition" ,parentId : 99 },
{id: 129 , fa:"داوینچی ریزالو" , en:"Davinci Resolve" ,parentId : 99 },
{id: 130 , fa:"اسپید تری" , en:"SpeedTree" ,parentId : 99 },
{id: 131 , fa:"مودو" , en:"Modo" ,parentId : 99 },
{id: 132 , fa:"ادوبی دایمنشن" , en:"Adobe Dimension" ,parentId : 99 },
{id: 133 , fa:"ادیوس" , en:"Edius" ,parentId : 99 },
{id: 134 , fa:"فاینال کات" , en:"Final Cut" ,parentId : 99 },
{id: 135 , fa:"کی شات" , en:"KeyShot" ,parentId : 99 },
{id: 136 , fa:"فیگما" , en:"Figma" ,parentId : 99 },
{id: 137 , fa:"شبکه و سخت افزار" , en:"Network and hardware" ,parentId:null },
{id: 138 , fa:"وایرشارک" , en:"Wireshark" ,parentId : 137 },
{id: 139 , fa:"سرور اطلاعات اینترنتی (آی آی اس)" , en:"IIS" ,parentId : 137 },
{id: 140 , fa:"سرور آی‌اس‌ای" , en:"ISA Server" ,parentId : 137 },
{id: 141 , fa:"جی اف آی لنگارد" , en:"GFI LAN GUARD" ,parentId : 137 },
{id: 142 , fa:"تی ام جی" , en:"TMG" ,parentId : 137 },
{id: 143 , fa:"جی اف آی وب مانیتور" , en:"GFI Web Monitor" ,parentId : 137 },
{id: 144 , fa:"اندپوینت" , en:"EndPoint" ,parentId : 137 },
{id: 145 , fa:"سولارویندز" , en:"Solar Winds" ,parentId : 137 },
{id: 146 , fa:"اکسچنج سرور" , en:"Exchange Server" ,parentId : 137 },
{id: 147 , fa:"اکتیو دایرکتوری" , en:"Active Directory" ,parentId : 137 },
{id: 148 , fa:"میکروتیک" , en:"Mikrotik" ,parentId : 137 },
{id: 149 , fa:"دی اچ سی پی" , en:"DHCP" ,parentId : 137 },
{id: 150 , fa:"دی ان اس ستینگ" , en:"DNS Settings" ,parentId : 137 },
{id: 151 , fa:"شرپوینت" , en:"SharePoint" ,parentId : 137 },
{id: 152 , fa:"وریلاگ" , en:"Verilog" ,parentId : 137 },
{id: 153 , fa:"وی اچ دی ال" , en:"VHDL" ,parentId : 137 },
{id: 154 , fa:"مدل سیم" , en:"Modelsim" ,parentId : 137 },
{id: 155 , fa:"کلود (فضای ابری)" , en:"Cloud" ,parentId : 137 },
{id: 156 , fa:"ای اس ایکس" , en:"ESX" ,parentId : 137 },
{id: 157 , fa:"مجازی سازی سرورها" , en:"Server virtualization" ,parentId : 137 },
{id: 158 , fa:"مجموعه نرم افزاری مدیریت مایکروسافت" , en:"SCOM (System Center Operations Manager)" ,parentId : 137 },
{id: 159 , fa:"سی سی ان ای" , en:"CCNA" ,parentId : 137 },
{id: 160 , fa:"سی سی ان پی" , en:"CCNP" ,parentId : 137 },
{id: 161 , fa:"سی سی آی ای" , en:"CCIE" ,parentId : 137 },
{id: 162 , fa:"جونیپر" , en:"JUNIPER" ,parentId : 137 },
{id: 163 , fa:"ام سی پی" , en:"MCP" ,parentId : 137 },
{id: 164 , fa:"ام سی اس ای" , en:"MCSA" ,parentId : 137 },
{id: 165 , fa:"ام پی ای اس" , en:"MPLS" ,parentId : 137 },
{id: 166 , fa:"مرکز تلفن سیسکو" , en:"Cisco Call Manager" ,parentId : 137 },
{id: 167 , fa:"فایروال PIX " , en:"Firewall PIX" ,parentId : 137 },
{id: 168 , fa:"روتینگ" , en:"Routing" ,parentId : 137 },
{id: 169 , fa:"سوییچینگ" , en:"Switching" ,parentId : 137 },
{id: 170 , fa:"ام تی سی ان ای" , en:"MTCNA" ,parentId : 137 },
{id: 171 , fa:"ام تی سی آر ای" , en:"MTCRE" ,parentId : 137 },
{id: 172 , fa:"ام تی سی تی سی ای" , en:"MTCTCE" ,parentId : 137 },
{id: 173 , fa:"ام تی سی یو ام ای" , en:"MTCUME" ,parentId : 137 },
{id: 174 , fa:"ام تی سی دابلیو ای" , en:"MTCWE" ,parentId : 137 },
{id: 175 , fa:"نتورک پلاس" , en:"Network+" ,parentId : 137 },
{id: 176 , fa:"ای پلاس" , en:"A+" ,parentId : 137 },
{id: 177 , fa:"پی آر تی جی" , en:"PRTG" ,parentId : 137 },
{id: 178 , fa:"سولارویندز" , en:"Solarwinds" ,parentId : 137 },
{id: 179 , fa:"زبیکس" , en:"Zabbix" ,parentId : 137 },
{id: 180 , fa:"ویم" , en:"Veeam" ,parentId : 137 },
{id: 181 , fa:"سی ای اچ" , en:"CEH" ,parentId : 137 },
{id: 182 , fa:"سکیوریتی پلاس" , en:"Security+" ,parentId : 137 },
{id: 183 , fa:"کریو" , en:"Kerio" ,parentId : 137 },
{id: 184 , fa:"نرم افزارهای مهندسی برق و مهندسی پزشکی" , en:"Electrical engineering and medical engineering software" ,parentId:null },
{id: 185 , fa:"آلتیوم دیزاینر" , en:"Altium Designer" ,parentId : 184 },
{id: 186 , fa:"اچ-اسپايس" , en:"Hspice" ,parentId : 184 },
{id: 187 , fa:"لب ویو" , en:"Labview" ,parentId : 184 },
{id: 188 , fa:"لاتکس" , en:"Latex" ,parentId : 184 },
{id: 189 , fa:"متلب" , en:"MATLAB" ,parentId : 184 },
{id: 190 , fa:"میکروویژن" , en:"Microvision" ,parentId : 184 },
{id: 191 , fa:"میمیکس" , en:"Mimics" ,parentId : 184 },
{id: 192 , fa:"مولتی سیم" , en:"Multisim" ,parentId : 184 },
{id: 193 , fa:"ارکد" , en:"Orcad" ,parentId : 184 },
{id: 194 , fa:"پروتئوس" , en:"Proteus" ,parentId : 184 },
{id: 195 , fa:"پی اس کد" , en:"Pscad" ,parentId : 184 },
{id: 196 , fa:"پی اس پایس" , en:"Pspice" ,parentId : 184 },
{id: 197 , fa:"ای پلن" , en:"Eplan" ,parentId : 184 },
{id: 198 , fa:"اتوکد الکتریکال" , en:"Autocad electrical" ,parentId : 184 },
{id: 199 , fa:"ای تپ" , en:"Etap" ,parentId : 184 },
{id: 200 , fa:"دیگسایلنت" , en:"Digsilent" ,parentId : 184 },
{id: 201 , fa:"سیماتیک منیجر" , en:"simatic manager" ,parentId : 184 },
{id: 202 , fa:"نرم افزار لوگو" , en:"LOGO! Soft" ,parentId : 184 },
{id: 203 , fa:"wpl سافت" , en:"Wplsoft" ,parentId : 184 },
{id: 204 , fa:"داپ سافت" , en:"Dopsoft" ,parentId : 184 },
{id: 205 , fa:"سی اس تی" , en:"CST" ,parentId : 184 },
{id: 206 , fa:"ای دی اس" , en:"ADS (Advanced Design Systems)" ,parentId : 184 },
{id: 207 , fa:"کادنس" , en:"Cadence" ,parentId : 184 },
{id: 208 , fa:"ان ماس" , en:"NMOS" ,parentId : 184 },
{id: 209 , fa:"فکت" , en:"FACT" ,parentId : 184 },
{id: 210 , fa:"ال ادیت" , en:"LEdit" ,parentId : 184 },
{id: 211 , fa:"تنر تولز" , en:"TannerTools" ,parentId : 184 },
{id: 212 , fa:"کد ویژن" , en:"CodeVision" ,parentId : 184 },
{id: 213 , fa:"آی ای آر" , en:"IAR Embedded WorkBench" ,parentId : 184 },
{id: 214 , fa:"اتمل استودیو" , en:"AtmelStudio" ,parentId : 184 },
{id: 215 , fa:"پی وی سیستم" , en:"PVSYST" ,parentId : 184 },
{id: 216 , fa:"وین سی سی" , en:"WinCC" ,parentId : 184 },
{id: 217 , fa:"نرم افزارهای مهندسی مکانیک و هوافضا" , en:"Mechanical and aerospace engineering software" ,parentId:null },
{id: 218 , fa:"نرم‌افزار تحلیل هواپیمای پیشرفته" , en:"AAA (Advanced Aircraft Analysis)" ,parentId : 217 },
{id: 219 , fa:"آباکوس" , en:"Abaqus" ,parentId : 217 },
{id: 220 , fa:"ادامز" , en:"Adams" ,parentId : 217 },
{id: 221 , fa:"آلتر هایپر ورکس" , en:"Altair HyperWorks" ,parentId : 217 },
{id: 222 , fa:"انسیس" , en:"Ansys" ,parentId : 217 },
{id: 223 , fa:"انسیس سی‌اف‌ایکس" , en:"Ansys CFX" ,parentId : 217 },
{id: 224 , fa:"انسیس توربو گرید" , en:"Ansys Turbo Grid" ,parentId : 217 },
{id: 225 , fa:"اسپن وان" , en:"AspenTech AspenONE" ,parentId : 217 },
{id: 226 , fa:"اتوداین" , en:"Autodyn" ,parentId : 217 },
{id: 227 , fa:"اتوپایپ" , en:"AutoPipe" ,parentId : 217 },
{id: 228 , fa:"اتوپلنت" , en:"AutoPlant" ,parentId : 217 },
{id: 229 , fa:"کدپایپ" , en:"CadPipe" ,parentId : 217 },
{id: 230 , fa:"cae پایپ" , en:"Caepipe" ,parentId : 217 },
{id: 231 , fa:"سزار" , en:"Caesar" ,parentId : 217 },
{id: 232 , fa:"کتیا" , en:"Catia" ,parentId : 217 },
{id: 233 , fa:"سی‌اف‌توربو" , en:"Cfturbo" ,parentId : 217 },
{id: 234 , fa:"کامسول" , en:"Comsol" ,parentId : 217 },
{id: 235 , fa:"کازماس" , en:"Cosmos" ,parentId : 217 },
{id: 236 , fa:"دت کام" , en:"Datcom" ,parentId : 217 },
{id: 237 , fa:"ای ای اس" , en:"EES - Engineering Equation Solver" ,parentId : 217 },
{id: 238 , fa:"فلومستر" , en:"Flowmaster" ,parentId : 217 },
{id: 239 , fa:"فلوئنت" , en:"Fluent" ,parentId : 217 },
{id: 240 , fa:"گمبیت" , en:"Gambit" ,parentId : 217 },
{id: 241 , fa:"هایپر مش" , en:"Hypermesh" ,parentId : 217 },
{id: 242 , fa:"اینورتور" , en:"Inventor" ,parentId : 217 },
{id: 243 , fa:"ال اس داینا" , en:"LS-DYNA" ,parentId : 217 },
{id: 244 , fa:"مارک" , en:"Marc" ,parentId : 217 },
{id: 245 , fa:"مکانیکال دسکتاپ" , en:"Mechanical Desktop" ,parentId : 217 },
{id: 246 , fa:"میکرواستیشن" , en:"Microstation" ,parentId : 217 },
{id: 247 , fa:"نسترن" , en:"Nastran" ,parentId : 217 },
{id: 248 , fa:"پاراسالید" , en:"Parasolid" ,parentId : 217 },
{id: 249 , fa:"پاتران" , en:"PATRAN" ,parentId : 217 },
{id: 250 , fa:"پی دی ام اس" , en:"PDMS" ,parentId : 217 },
{id: 251 , fa:"پرو انجینیر" , en:"Pro Engineer" ,parentId : 217 },
{id: 252 , fa:"سالیدورکز" , en:"Solidworks" ,parentId : 217 },
{id: 253 , fa:"وی ال ای" , en:"VLA" ,parentId : 217 },
{id: 254 , fa:"ورکینگ مدل" , en:"Working Model" ,parentId : 217 },
{id: 255 , fa:"ایکس فویل" , en:"XFoil" ,parentId : 217 },
{id: 256 , fa:"پاورمیل" , en:"PowerMill" ,parentId : 217 },
{id: 257 , fa:"تحلیل ساعتی کریر" , en:"Carrier HAP" ,parentId : 217 },
{id: 258 , fa:"ای وی ال فایل" , en:"AVL Fire" ,parentId : 217 },
{id: 259 , fa:"نرم افزارهای مهندسی معدن و مواد" , en:"Mining and materials engineering software" ,parentId:null },
{id: 260 , fa:"آرک وبو" , en:"ARC View" ,parentId : 259 },
{id: 261 , fa:"آرک جی‌آی‌اس" , en:"ARCGIS" ,parentId : 259 },
{id: 262 , fa:"دیتاماین استودیو" , en:"Datamine Studio" ,parentId : 259 },
{id: 263 , fa:"دیپز" , en:"Dips" ,parentId : 259 },
{id: 264 , fa:"داون هول اکسپلورر" , en:"Downhole Explorer" ,parentId : 259 },
{id: 265 , fa:"انوی" , en:"ENVI" ,parentId : 259 },
{id: 266 , fa:"ار مپر یو دی ای سی" , en:"ErmapperUDEC" ,parentId : 259 },
{id: 267 , fa:"فلک" , en:"FLAC" ,parentId : 259 },
{id: 268 , fa:"جمز" , en:"GEMS" ,parentId : 259 },
{id: 269 , fa:"ژئو تکنیکال گرافیکز" , en:"GeoTechnical Graphics" ,parentId : 259 },
{id: 270 , fa:"ایتاسکا 3 دک" , en:"Itasca 3DEC" ,parentId : 259 },
{id: 271 , fa:"لاگ پلات" , en:"LOG PLOT" ,parentId : 259 },
{id: 272 , fa:"لاگ میت" , en:"LogMate" ,parentId : 259 },
{id: 273 , fa:"ماین اسکود" , en:"MineSched" ,parentId : 259 },
{id: 274 , fa:"ماین سایت" , en:"MineSight" ,parentId : 259 },
{id: 275 , fa:"ماینکس" , en:"Minex" ,parentId : 259 },
{id: 276 , fa:"فاز 2" , en:"Phase2" ,parentId : 259 },
{id: 277 , fa:"کوییک لاگ" , en:"Quick log" ,parentId : 259 },
{id: 278 , fa:"راک پلن" , en:"Rock Plane" ,parentId : 259 },
{id: 279 , fa:"راک ورک" , en:"Rockwork" ,parentId : 259 },
{id: 280 , fa:"راک لب" , en:"ROCLAB" ,parentId : 259 },
{id: 281 , fa:"اسلاید" , en:"SLIDE" ,parentId : 259 },
{id: 282 , fa:"استریونت" , en:"Stereonet" ,parentId : 259 },
{id: 283 , fa:"سرفر" , en:"Surfer" ,parentId : 259 },
{id: 284 , fa:"سورپک" , en:"Surpac" ,parentId : 259 },
{id: 285 , fa:"سووج" , en:"Swedge" ,parentId : 259 },
{id: 286 , fa:"تارگت" , en:"target" ,parentId : 259 },
{id: 287 , fa:"وولکان" , en:"Vulcan" ,parentId : 259 },
{id: 288 , fa:"ویتل" , en:"Whittle" ,parentId : 259 },
{id: 289 , fa:"نرم افزارهای مهندسی صنایع و مدیریت" , en:"Industrial engineering and management software" ,parentId:null },
{id: 290 , fa:"ایس پلنر" , en:"Ace Planner" ,parentId : 289 },
{id: 291 , fa:"بهبود استقرار تجهیزات" , en:"VIP-PLANOPT" ,parentId : 289 },
{id: 292 , fa:"انی لاجیک" , en:"AnyLogic" ,parentId : 289 },
{id: 293 , fa:"آرنا" , en:"Arena" ,parentId : 289 },
{id: 294 , fa:"حل کننده AIMMS" , en:"AIMMS Solver" ,parentId : 289 },
{id: 295 , fa:"کامفار" , en:"COMFAR" ,parentId : 289 },
{id: 296 , fa:"کاملند" , en:"COMLAND" ,parentId : 289 },
{id: 297 , fa:"دی بی 2" , en:"DB2" ,parentId : 289 },
{id: 298 , fa:"دی اس" , en:"DS" ,parentId : 289 },
{id: 299 , fa:"داینامو" , en:"DYNAMO" ,parentId : 289 },
{id: 300 , fa:"ایزی کیس" , en:"Easy Case" ,parentId : 289 },
{id: 301 , fa:"اروین استلا" , en:"Erwin Stella" ,parentId : 289 },
{id: 302 , fa:"اکسپرت چویس" , en:"Expert Choice" ,parentId : 289 },
{id: 303 , fa:"فلکسیم" , en:"Flexim" ,parentId : 289 },
{id: 304 , fa:"فازی ژن" , en:"Fuzzy Gen" ,parentId : 289 },
{id: 305 , fa:"گمز" , en:"Gams" ,parentId : 289 },
{id: 306 , fa:"گسپ" , en:"GASP" ,parentId : 289 },
{id: 307 , fa:"جینو" , en:"GINO" ,parentId : 289 },
{id: 308 , fa:"جی پی اس اس" , en:"GPSS" ,parentId : 289 },
{id: 309 , fa:"اینفورمیکس" , en:"INFORMIX" ,parentId : 289 },
{id: 310 , fa:"اینگرس" , en:"INGRES" ,parentId : 289 },
{id: 311 , fa:"لیندو" , en:"LINDO" ,parentId : 289 },
{id: 312 , fa:"لینگو" , en:"LINGO" ,parentId : 289 },
{id: 313 , fa:"مانی مکسیمایزر" , en:"Money Maximizer" ,parentId : 289 },
{id: 314 , fa:"ام پی سی اس" , en:"MPCS" ,parentId : 289 },
{id: 315 , fa:"ام پی ال" , en:"MPL" ,parentId : 289 },
{id: 316 , fa:"ام پی پی زد آی" , en:"MPPZI" ,parentId : 289 },
{id: 317 , fa:"ام آر پی" , en:"MRP" ,parentId : 289 },
{id: 318 , fa:"ام وای او بی" , en:"MYOB" ,parentId : 289 },
{id: 319 , fa:"او پی تی" , en:"OPT" ,parentId : 289 },
{id: 320 , fa:"پی ال اس" , en:"PLS" ,parentId : 289 },
{id: 321 , fa:"پاور دیزاینر" , en:"Power Designer" ,parentId : 289 },
{id: 322 , fa:"پریماورا" , en:"Primavera" ,parentId : 289 },
{id: 323 , fa:"مدیریت پروژه" , en:"Production Manager" ,parentId : 289 },
{id: 324 , fa:"زمانبندی پروژه" , en:"Project Scheduler" ,parentId : 289 },
{id: 325 , fa:"کیو سام" , en:"QSom" ,parentId : 289 },
{id: 326 , fa:"رشنال رز" , en:"Rational Suite Enterprise" ,parentId : 289 },
{id: 327 , fa:"سیم اسکریپت" , en:"SIMSCRIPT" ,parentId : 289 },
{id: 328 , fa:"سیمول 8" , en:"SIMUL8" ,parentId : 289 },
{id: 329 , fa:"سیمولا" , en:"SIMULA" ,parentId : 289 },
{id: 330 , fa:"اسلم" , en:"SLAM" ,parentId : 289 },
{id: 331 , fa:"اس او ال" , en:"SOL" ,parentId : 289 },
{id: 332 , fa:"اس کیو ال /  دی اس" , en:"SQL/DS" ,parentId : 289 },
{id: 333 , fa:"استلار" , en:"Stellat" ,parentId : 289 },
{id: 334 , fa:"استورم" , en:"STORM" ,parentId : 289 },
{id: 335 , fa:"اس وای بیس" , en:"SYBASE" ,parentId : 289 },
{id: 336 , fa:"تحلیل سیستم ها" , en:"System Analysis" ,parentId : 289 },
{id: 337 , fa:"تیلور" , en:"Taylor" ,parentId : 289 },
{id: 338 , fa:"ترا" , en:"TORA" ,parentId : 289 },
{id: 339 , fa:"ونسیم" , en:"Vensim" ,parentId : 289 },
{id: 340 , fa:"WBS پرو" , en:"WBS Pro" ,parentId : 289 },
{id: 341 , fa:"وین گمز" , en:"WINGAMS" ,parentId : 289 },
{id: 342 , fa:"وین کیو اس بی" , en:"WinQSB" ,parentId : 289 },
{id: 343 , fa:"وینستون" , en:"Winston" ,parentId : 289 },
{id: 344 , fa:"بیزاجی" , en:"Bizagi" ,parentId : 289 },
{id: 345 , fa:"اسلک" , en:"Slack" ,parentId : 289 },
{id: 346 , fa:"ترللو" , en:"Trello" ,parentId : 289 },
{id: 347 , fa:"نرم افزارهای معماری و شهرسازی" , en:"Architecture and urban planning software" ,parentId:null },
{id: 348 , fa:"آرشیکد" , en:"Archicad" ,parentId : 347 },
{id: 349 , fa:"اتوکد" , en:"AutoCad" ,parentId : 347 },
{id: 350 , fa:"گرس هاپر" , en:"Grasshopper" ,parentId : 347 },
{id: 351 , fa:"لومیون" , en:"Lumion" ,parentId : 347 },
{id: 352 , fa:"پست پروداکشن" , en:"Post Production" ,parentId : 347 },
{id: 353 , fa:"رویت" , en:"Revit" ,parentId : 347 },
{id: 354 , fa:"رینو" , en:"Rhino" ,parentId : 347 },
{id: 355 , fa:"اسکچ آپ" , en:"Sketchup" ,parentId : 347 },
{id: 356 , fa:"وی ری" , en:"Vray" ,parentId : 347 },
{id: 357 , fa:"نرم افزارهای مهندسی عمران" , en:"Civil engineering software" ,parentId:null },
{id: 358 , fa:"سیویل 3D" , en:"Autocad Civil 3D" ,parentId : 357 },
{id: 359 , fa:"کانواس" , en:"Canvas" ,parentId : 357 },
{id: 360 , fa:"سی اس آی بریج" , en:"CSI Bridge" ,parentId : 357 },
{id: 361 , fa:"ایتبس" , en:"ETABS" ,parentId : 357 },
{id: 362 , fa:"فلک 3D" , en:"FLAC 3D" ,parentId : 357 },
{id: 363 , fa:"لوساس" , en:"Lusas" ,parentId : 357 },
{id: 364 , fa:"اپنسیس" , en:"Opensees" ,parentId : 357 },
{id: 365 , fa:"پرفورم" , en:"Perform" ,parentId : 357 },
{id: 366 , fa:"پلکسیس" , en:"Plaxis Professional" ,parentId : 357 },
{id: 367 , fa:"سیف" , en:"Safe" ,parentId : 357 },
{id: 368 , fa:"سم لیپ" , en:"SAM LEAP" ,parentId : 357 },
{id: 369 , fa:"سپ 2000" , en:"SAP2357" ,parentId : 357 },
{id: 370 , fa:"سکشن بیلدر" , en:"Section Builder" ,parentId : 357 },
{id: 371 , fa:"سازه 90" , en:"SAZE90" ,parentId : 357 },
{id: 372 , fa:"ناویس ورکس" , en:"Navisworks" ,parentId : 357 },
{id: 373 , fa:"تدکار" , en:"Tadkar Software" ,parentId : 357 },
{id: 374 , fa:"تکلااستراکچرز" , en:"Tekla Structures" ,parentId : 357 },
{id: 375 , fa:"نرم افزارهای مهندسی شیمی، نفت و پلیمر" , en:"Chemical, petroleum and polymer engineering software" ,parentId:null },
{id: 376 , fa:"ای اف تی " , en:"AFT Fathom(Applied Flow Technology Fathom)" ,parentId : 375 },
{id: 377 , fa:"اسپن هایسیس" , en:"Aspen HYSYS" ,parentId : 375 },
{id: 378 , fa:"آسپن میوس" , en:"Aspen MUSE" ,parentId : 375 },
{id: 379 , fa:"اسپن آنلاین" , en:"Aspen OnLine" ,parentId : 375 },
{id: 380 , fa:"اسپن پیمز" , en:"Aspen PIMS" ,parentId : 375 },
{id: 381 , fa:"اسپن پلاس" , en:"Aspen plus" ,parentId : 375 },
{id: 382 , fa:"اسپن پروسس منوال" , en:"Aspen Process Manual" ,parentId : 375 },
{id: 383 , fa:"آووست" , en:"Avocet" ,parentId : 375 },
{id: 384 , fa:"کم کد" , en:"ChemCad" ,parentId : 375 },
{id: 385 , fa:"کم آفیس" , en:"ChemOffice" ,parentId : 375 },
{id: 386 , fa:"سی ام جی" , en:"CMG" ,parentId : 375 },
{id: 387 , fa:"پی وی الیت" , en:"COADE PVElite" ,parentId : 375 },
{id: 388 , fa:"دریلینگ آفیس" , en:"Drilling Office" ,parentId : 375 },
{id: 389 , fa:"اکلیپس" , en:"Eclips" ,parentId : 375 },
{id: 390 , fa:"اکونومیک اوالوشن" , en:"Economic Evaluation" ,parentId : 375 },
{id: 391 , fa:"اکسید" , en:"Exceed" ,parentId : 375 },
{id: 392 , fa:"طراحی مبدل و رتبه بندی" , en:"Exchanger Design and Rating" ,parentId : 375 },
{id: 393 , fa:"ژئوفریم" , en:"Geoframe" ,parentId : 375 },
{id: 394 , fa:"ژئولاگ" , en:"Geolog" ,parentId : 375 },
{id: 395 , fa:"هایسیس" , en:"Hysis" ,parentId : 375 },
{id: 396 , fa:"اینونسیس" , en:"Invensys SimSci-Esscor PIPEPHASE" ,parentId : 375 },
{id: 397 , fa:"آی پی ام پکیج" , en:"IPM Package" ,parentId : 375 },
{id: 398 , fa:"لندمارک پکیج" , en:"Landmark Package" ,parentId : 375 },
{id: 399 , fa:"اوپریشن ساپورت" , en:"Operations Support" ,parentId : 375 },
{id: 400 , fa:"پترل" , en:"Petrel" ,parentId : 375 },
{id: 401 , fa:"پترل انجینیرینگ" , en:"Petrol Engineering" ,parentId : 375 },
{id: 402 , fa:"پایپ سیم" , en:"Pipesim" ,parentId : 375 },
{id: 403 , fa:"فرایند توسعه نرم افزار" , en:"Process Development" ,parentId : 375 },
{id: 404 , fa:"سالید واکس" , en:"Solid vox" ,parentId : 375 },
{id: 405 , fa:"سیس دریل" , en:"Sysdrill" ,parentId : 375 },
{id: 406 , fa:"الگا" , en:"olga" ,parentId : 375 },
{id: 407 , fa:"نرم افزارهای مالی و حسابداری" , en:"Financial and accounting software" ,parentId:null },
{id: 408 , fa:"همکاران سیستم" , en:"hamkaran" ,parentId : 407 },
{id: 409 , fa:"رایورز" , en:"rayvarz" ,parentId : 407 },
{id: 410 , fa:"تدبیر" , en:"tadbir" ,parentId : 407 },
{id: 411 , fa:"هلو" , en:"holoo" ,parentId : 407 },
{id: 412 , fa:"شایگان" , en:"shygunsys" ,parentId : 407 },
{id: 413 , fa:"رافع" , en:"rafe" ,parentId : 407 },
{id: 414 , fa:"میزان" , en:"mizan" ,parentId : 407 },
{id: 415 , fa:"سپیدار" , en:"sepidar" ,parentId : 407 },
{id: 416 , fa:"سیاق" , en:"seyagh" ,parentId : 407 },
{id: 417 , fa:"قیاس" , en:"gheyas" ,parentId : 407 },
{id: 418 , fa:"ویژن" , en:"vision" ,parentId : 407 },
{id: 419 , fa:"فن‌ آوران صدور بیمه‌ نامه" , en:"Fanavaran Insurance issuance" ,parentId : 407 },
{id: 420 , fa:"شماران سیستم" , en:"shomaran system" ,parentId : 407 },
{id: 421 , fa:"راهکاران" , en:"rahkaran" ,parentId : 407 },
{id: 422 , fa:"رایان هم افزا" , en:"rayan ham afza" ,parentId : 407 },
{id: 423 , fa:"پیوست" , en:"payvast" ,parentId : 407 },
{id: 424 , fa:"ورانگر" , en:"varanegar" ,parentId : 407 },
{id: 425 , fa:"آسا" , en:"asa system" ,parentId : 407 },
{id: 426 , fa:"پارسیان" , en:"parsian" ,parentId : 407 },
{id: 427 , fa:"نرم افزارهای آماری و تحلیل داده" , en:"Statistical software and data analysis" ,parentId:null },
{id: 428 , fa:"آکسوم" , en:"Axume" ,parentId : 427 },
{id: 429 , fa:"بی ام دی پی" , en:"BMDP" ,parentId : 427 },
{id: 430 , fa:"آنالیز ESBPDF" , en:"ESBPDF Analysis" ,parentId : 427 },
{id: 431 , fa:"ESB استیت" , en:"ESBStats" ,parentId : 427 },
{id: 432 , fa:"ای ویوز" , en:"EViews" ,parentId : 427 },
{id: 433 , fa:"جنستات" , en:"Genstat" ,parentId : 427 },
{id: 434 , fa:"جی ام پی" , en:"JMP" ,parentId : 427 },
{id: 435 , fa:"لیمدپ" , en:"Limdep" ,parentId : 427 },
{id: 436 , fa:"لیزرل" , en:"LISREL" ,parentId : 427 },
{id: 437 , fa:"میپل" , en:"MAPLE" ,parentId : 427 },
{id: 438 , fa:"مث کَد" , en:"Mathcad" ,parentId : 427 },
{id: 439 , fa:"متمتیکا" , en:"Mathematica" ,parentId : 427 },
{id: 440 , fa:"مکس استار" , en:"Maxstat" ,parentId : 427 },
{id: 441 , fa:"مینی تب" , en:"Minitab" ,parentId : 427 },
{id: 442 , fa:"ان سی اس اس" , en:"NCSS" ,parentId : 427 },
{id: 443 , fa:"پی اچ استت" , en:"PHStat" ,parentId : 427 },
{id: 444 , fa:"آر (زبان برنامه نویسی)" , en:"R (Programming Language)" ,parentId : 427 },
{id: 445 , fa:"سس" , en:"SAS" ,parentId : 427 },
{id: 446 , fa:"سیگماپلات" , en:"SigmaPlot" ,parentId : 427 },
{id: 447 , fa:"سیگمااستت" , en:"Sigmastat" ,parentId : 427 },
{id: 448 , fa:"اس پی سی" , en:"SPC" ,parentId : 427 },
{id: 449 , fa:"اس پلاس" , en:"S-Plus" ,parentId : 427 },
{id: 450 , fa:"اس پی اس اس" , en:"SPSS" ,parentId : 427 },
{id: 451 , fa:"استاتا" , en:"Stata" ,parentId : 427 },
{id: 452 , fa:"استت گرافیکز" , en:"Statgraphics" ,parentId : 427 },
{id: 453 , fa:"استاتیستیکا" , en:"Statistica" ,parentId : 427 },
{id: 454 , fa:"استیشس" , en:"Statius" ,parentId : 427 },
{id: 455 , fa:"استاتس دایرکت" , en:"StatsDirect" ,parentId : 427 },
{id: 456 , fa:"سیستات" , en:"Systat" ,parentId : 427 },
{id: 457 , fa:"ایموس" , en:"Amos" ,parentId : 427 },
{id: 458 , fa:"آر" , en:"R" ,parentId : 427 },
{id: 459 , fa:"سیستم عامل" , en:"Operating System" ,parentId:null },
{id: 460 , fa:"ویندوز سرور" , en:"Windows Server" ,parentId : 459 },
{id: 461 , fa:"اوبونتو (لینوکس)" , en:"Ubuntu (Linux)" ,parentId : 459 },
{id: 462 , fa:"مک او اس" , en:"Mac OS" ,parentId : 459 },
{id: 463 , fa:"دبیان (لینوکس)" , en:"Debian (Linux)" ,parentId : 459 },
{id: 464 , fa:"فدورا (لینوکس)" , en:"Fedora (Linux)" ,parentId : 459 },
{id: 465 , fa:"رد هت (لینوکس)" , en:"Red Hat (Linux)" ,parentId : 459 },
{id: 466 , fa:"مک او اس ایکس" , en:"OS X" ,parentId : 459 },
{id: 467 , fa:"لینوکس" , en:"Linux" ,parentId : 459 },
{id: 468 , fa:"آرچ لینوکس" , en:"Arch Based Distributions (Linux)" ,parentId : 459 },
{id: 469 , fa:"مدیریت ارتباط با مشتری - CRM" , en:"Customer Relationship Management - CRM" ,parentId:null },
{id: 470 , fa:"مایکروسافت داینامیک" , en:"Microsoft Dynamics CRM" ,parentId : 469 },
{id: 471 , fa:"سیلز فورس" , en:"Sales Force" ,parentId : 469 },
{id: 472 , fa:"شوگر سی آر ام" , en:"Sugar CRM" ,parentId : 469 },
{id: 473 , fa:"دیدار" , en:"didar CRM" ,parentId : 469 },
{id: 474 , fa:"سرو" , en:"Sarv CRM" ,parentId : 469 },
{id: 475 , fa:"پیام گستر" , en:"Payamgostar CRM" ,parentId : 469 },
{id: 476 , fa:"روش" , en:"Ravesh CRM" ,parentId : 469 },
{id: 477 , fa:"ایده آل" , en:"Ideal CRM" ,parentId : 469 },
{id: 478 , fa:"نرم افزار ERP" , en:"ERP software" ,parentId:null },
{id: 479 , fa:"سپ" , en:"SAP" ,parentId : 478 },
{id: 480 , fa:"اوراکل" , en:"Oracle" ,parentId : 478 },
{id: 481 , fa:"مایکروسافت" , en:"Microsoft" ,parentId : 478 },
{id: 482 , fa:"لوگو" , en:"Logo" ,parentId : 478 },
{id: 483 , fa:"آی اف اس" , en:"IFS" ,parentId : 478 },
{id: 484 , fa:"نرم افزار های مدیریت محتوا" , en:"Content management software" ,parentId:null },
{id: 485 , fa:"وردپرس" , en:"Wordpress" ,parentId : 484 },
{id: 486 , fa:"جوملا" , en:"Joomla" ,parentId : 484 },
{id: 487 , fa:"دروپال" , en:"Drupal" ,parentId : 484 },
{id: 488 , fa:"گوگل تگ منیجر" , en:"Google Tag Manager" ,parentId : 484 },
{id: 489 , fa:"گوگل سرچ کنسول" , en:"Google Search Console" ,parentId : 484 },
{id: 490 , fa:"نرم افزارهای پایگاه داده" , en:"Database software" ,parentId:null },
{id: 491 , fa:"اس کیو ال سرور" , en:"Sql Server" ,parentId : 490 },
{id: 492 , fa:"مای اس کیو ال" , en:"MySql" ,parentId : 490 },
{id: 493 , fa:"پستگرس کیو ال" , en:"PostgreSql" ,parentId : 490 },
{id: 494 , fa:"اوراکل دیتابیس" , en:"Oracle Database" ,parentId : 490 },
{id: 495 , fa:"مانگو دی‌بی" , en:"MongoDB" ,parentId : 490 },
{id: 496 , fa:"کاساندرا" , en:"Cassandra" ,parentId : 490 },
{id: 497 , fa:"نئو 4جی" , en:"Neo4j" ,parentId : 490 },
{id: 498 , fa:"اوراکل NoSQL" , en:"Oracle NoSQL" ,parentId : 490 },
{id: 499 , fa:"کوچ بیس" , en:"Couchbase" ,parentId : 490 },
{id: 500 , fa:"کوچ دی بی" , en:"CouchDB" ,parentId : 490 },
{id: 501 , fa:"نرم افزارهای داده کاوی و بیگ دیتا" , en:"Data mining and big data software" ,parentId:null },
{id: 502 , fa:"رپید ماینر" , en:"Rapid Miner" ,parentId : 501 },
{id: 503 , fa:"نایم" , en:"Knime" ,parentId : 501 },
{id: 504 , fa:"کلیک ویو" , en:"Qlikview" ,parentId : 501 },
{id: 505 , fa:"کلیک سنس" , en:"Qliksense" ,parentId : 501 },
{id: 506 , fa:"تبلو" , en:"Tableau" ,parentId : 501 },
{id: 507 , fa:"پاور بی آی" , en:"PowerBI" ,parentId : 501 },
{id: 508 , fa:"اس اس آی اس" , en:"SSIS" ,parentId : 501 },
{id: 509 , fa:"اس اس آر اس" , en:"SSRS" ,parentId : 501 },
{id: 510 , fa:"اس اس ای اس" , en:"SSAS" ,parentId : 501 },
{id: 511 , fa:"هادوپ" , en:"Hadoop" ,parentId : 501 },
{id: 512 , fa:"اچ بیس" , en:"Hbase" ,parentId : 501 },
{id: 513 , fa:"مپ رجیس" , en:"MapReduce" ,parentId : 501 },
{id: 514 , fa:"ردیس" , en:"Redis" ,parentId : 501 },
{id: 515 , fa:"اسپارک" , en:"Spark" ,parentId : 501 },
{id: 516 , fa:"زوکیپر" , en:"Zookeeper" ,parentId : 501 },
{id: 517 , fa:"کلودرا" , en:"Cloudera" ,parentId : 501 },
{id: 518 , fa:"وکا" , en:"Weka" ,parentId : 501 },
{id: 519 , fa:"اوراکل بی آی" , en:"Oracle BI" ,parentId : 501 },
{id: 520 , fa:"ادی" , en:"ODI" ,parentId : 501 },
{id: 521 , fa:"بازی" , en:"game" ,parentId:null },
{id: 522 , fa:"یونیتی" , en:"Unity" ,parentId : 521 },
{id: 523 , fa:"کورونا اس دی کا" , en:"Corona SDK" ,parentId : 521 },
{id: 524 , fa:"اسپرایت کیت" , en:"SpriteKit" ,parentId : 521 },
{id: 525 , fa:"اپ گیم کیت" , en:"AppGameKit" ,parentId : 521 },
{id: 526 , fa:"کنستراکت 2" , en:"Construct 2" ,parentId : 521 },
{id: 527 , fa:"مونو گیم" , en:"MonoGame" ,parentId : 521 },
{id: 528 , fa:"کو کوز 2دی" , en:"Cocos2D" ,parentId : 521 },
{id: 529 , fa:"گیدرس" , en:"Gideros" ,parentId : 521 },
{id: 530 , fa:"هکس" , en:"Haxe" ,parentId : 521 },
{id: 531 , fa:"آنریل انجین" , en:"Unreal Engine" ,parentId : 521 },
{id: 532 , fa:"گیم میکر" , en:"GameMaker" ,parentId : 521 },
{id: 533 , fa:"ترک 3دی" , en:"Torque 3D" ,parentId : 521 },
{id: 534 , fa:"بیلد باکس" , en:"Buildbox" ,parentId : 521 },
]


export const beseUrl='http://192.168.1.102'
